//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVE.VS.FeedbackGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class SessionManager {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SessionManager() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaVE.VS.FeedbackGenerator.Properties.SessionManager", typeof(SessionManager).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Design.
        /// </summary>
        public static string DesignView {
            get {
                return ResourceManager.GetString("DesignView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selektiere Event für mehr Details.
        /// </summary>
        public static string DetailsForSingleSelectedEvent {
            get {
                return ResourceManager.GetString("DetailsForSingleSelectedEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selektiere Session für mehr Details.
        /// </summary>
        public static string DetailsForSingleSelectedSession {
            get {
                return ResourceManager.GetString("DetailsForSingleSelectedSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Document.
        /// </summary>
        public static string EventActiveDocument {
            get {
                return ResourceManager.GetString("EventActiveDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active Window.
        /// </summary>
        public static string EventActiveWindow {
            get {
                return ResourceManager.GetString("EventActiveWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kontext.
        /// </summary>
        public static string EventContext {
            get {
                return ResourceManager.GetString("EventContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Data.
        /// </summary>
        public static string EventData {
            get {
                return ResourceManager.GetString("EventData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewählte Event(s) löschen.
        /// </summary>
        public static string EventDelete {
            get {
                return ResourceManager.GetString("EventDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie die gewählten {0} Events löschen wollen?.
        /// </summary>
        public static string EventDeleteConfirmPlural {
            get {
                return ResourceManager.GetString("EventDeleteConfirmPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie das gewählte Event löschen wollen?.
        /// </summary>
        public static string EventDeleteConfirmSingular {
            get {
                return ResourceManager.GetString("EventDeleteConfirmSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event(s) löschen.
        /// </summary>
        public static string EventDeleteConfirmTitle {
            get {
                return ResourceManager.GetString("EventDeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        public static string EventDetails {
            get {
                return ResourceManager.GetString("EventDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duration.
        /// </summary>
        public static string EventDuration {
            get {
                return ResourceManager.GetString("EventDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ms.
        /// </summary>
        public static string EventDurationUnit {
            get {
                return ResourceManager.GetString("EventDurationUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vorschläge.
        /// </summary>
        public static string EventProposals {
            get {
                return ResourceManager.GetString("EventProposals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Events.
        /// </summary>
        public static string Events {
            get {
                return ResourceManager.GetString("Events", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ausgewählt.
        /// </summary>
        public static string EventSelection {
            get {
                return ResourceManager.GetString("EventSelection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start.
        /// </summary>
        public static string EventTime {
            get {
                return ResourceManager.GetString("EventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event Trigger.
        /// </summary>
        public static string EventTrigger {
            get {
                return ResourceManager.GetString("EventTrigger", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type.
        /// </summary>
        public static string EventType {
            get {
                return ResourceManager.GetString("EventType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starts the Export Wizard....
        /// </summary>
        public static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Wizard.
        /// </summary>
        public static string Export_Button {
            get {
                return ResourceManager.GetString("Export_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Feedback.
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie die Einstellungen zurücksetzen und das lokal gesammelte Feedback löschen wollen?.
        /// </summary>
        public static string Option_SettingsCleaner_Dialog {
            get {
                return ResourceManager.GetString("Option_SettingsCleaner_Dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bitte geben Sie ein gültige HTTP- oder HTTPS-URL ein..
        /// </summary>
        public static string OptionPageErrorMessage {
            get {
                return ResourceManager.GetString("OptionPageErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opens the options page....
        /// </summary>
        public static string Options {
            get {
                return ResourceManager.GetString("Options", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Options.
        /// </summary>
        public static string Options_Button {
            get {
                return ResourceManager.GetString("Options_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Exportoptionen bestimmen, welche Feedback-Details Ihren Rechner beim Export verlassen. Lokal wird das Feedback immer vollständig aufgenommen, um Ihnen die Einsicht zu erleichtern. Wenn Sie die Wirkung der Exportoptionen prüfen wollen, exportieren Sie einfach in ein ZIP-Archiv zum manuellen Hochladen. Diese Archive enthalten alle exportierten Informationen im Klartext..
        /// </summary>
        public static string Options_Export_Disclaimer {
            get {
                return ResourceManager.GetString("Options_Export_Disclaimer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projektzugehörige Code-Bezeichner aus Events entfernen.
        /// </summary>
        public static string Options_Export_RemoveCodeNames {
            get {
                return ResourceManager.GetString("Options_Export_RemoveCodeNames", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dauer von Events entfernen.
        /// </summary>
        public static string Options_Export_RemoveDurations {
            get {
                return ResourceManager.GetString("Options_Export_RemoveDurations", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessionzuordnung aus Events entfernen.
        /// </summary>
        public static string Options_Export_RemoveSessionIDs {
            get {
                return ResourceManager.GetString("Options_Export_RemoveSessionIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Startzeit von Events entfernen.
        /// </summary>
        public static string Options_Export_RemoveStartTimes {
            get {
                return ResourceManager.GetString("Options_Export_RemoveStartTimes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportoptionen.
        /// </summary>
        public static string Options_Export_Title {
            get {
                return ResourceManager.GetString("Options_Export_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload URL.
        /// </summary>
        public static string Options_Export_UploadUrl {
            get {
                return ResourceManager.GetString("Options_Export_UploadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Präfix für Web-Zugriff.
        /// </summary>
        public static string Options_Export_WebAccessPraefix {
            get {
                return ResourceManager.GetString("Options_Export_WebAccessPraefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to KaVE Feedback.
        /// </summary>
        public static string Options_Title {
            get {
                return ResourceManager.GetString("Options_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON.
        /// </summary>
        public static string RawView {
            get {
                return ResourceManager.GetString("RawView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refreshes the list of sessions.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aktualisieren.
        /// </summary>
        public static string Refresh_Button {
            get {
                return ResourceManager.GetString("Refresh_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lade Feedback.
        /// </summary>
        public static string Refreshing {
            get {
                return ResourceManager.GetString("Refreshing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip files (*.zip)|*.zip|All files (*.*)|*.*.
        /// </summary>
        public static string SaveFileDialogFilter {
            get {
                return ResourceManager.GetString("SaveFileDialogFilter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback versenden.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day.
        /// </summary>
        public static string Session {
            get {
                return ResourceManager.GetString("Session", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag der Session.
        /// </summary>
        public static string SessionDay {
            get {
                return ResourceManager.GetString("SessionDay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gewählte Session(s) löschen.
        /// </summary>
        public static string SessionDelete {
            get {
                return ResourceManager.GetString("SessionDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie die gewählten {0} Sessions löschen wollen?.
        /// </summary>
        public static string SessionDeleteConfirmPlural {
            get {
                return ResourceManager.GetString("SessionDeleteConfirmPlural", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sind Sie sicher, dass Sie die gewählte Session löschen wollen?.
        /// </summary>
        public static string SessionDeleteConfirmSingular {
            get {
                return ResourceManager.GetString("SessionDeleteConfirmSingular", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session(s) löschen.
        /// </summary>
        public static string SessionDeleteConfirmTitle {
            get {
                return ResourceManager.GetString("SessionDeleteConfirmTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sessions.
        /// </summary>
        public static string Sessions {
            get {
                return ResourceManager.GetString("Sessions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the official website of the project.
        /// </summary>
        public static string VisitHomepage {
            get {
                return ResourceManager.GetString("VisitHomepage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Website.
        /// </summary>
        public static string VisitHomepage_Button {
            get {
                return ResourceManager.GetString("VisitHomepage_Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die Webseite zum manuellen Hochladen von Feedback öffnen....
        /// </summary>
        public static string VisitUploadPage {
            get {
                return ResourceManager.GetString("VisitUploadPage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Website for Manual Upload.
        /// </summary>
        public static string VisitUploadPage_Button {
            get {
                return ResourceManager.GetString("VisitUploadPage_Button", resourceCulture);
            }
        }
    }
}
