//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVE.VS.FeedbackGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UploadWizard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UploadWizard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaVE.VS.FeedbackGenerator.Properties.UploadWizard", typeof(UploadWizard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymization.
        /// </summary>
        public static string anonymization_link {
            get {
                return ResourceManager.GetString("anonymization_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can close the dialog anytime, the export continues in the background..
        /// </summary>
        public static string CloseWizardDuringExportHint {
            get {
                return ResourceManager.GetString("CloseWizardDuringExportHint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3/4: Compression.
        /// </summary>
        public static string CompressingEvents {
            get {
                return ResourceManager.GetString("CompressingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The export continues in the background..
        /// </summary>
        public static string ContinueInBackground {
            get {
                return ResourceManager.GetString("ContinueInBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exporting Events.
        /// </summary>
        public static string Export_BusyMessage {
            get {
                return ResourceManager.GetString("Export_BusyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direct Upload.
        /// </summary>
        public static string export_upload_button {
            get {
                return ResourceManager.GetString("export_upload_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP-Export....
        /// </summary>
        public static string export_zip_button {
            get {
                return ResourceManager.GetString("export_zip_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred during the export/upload of the feedback!.
        /// </summary>
        public static string ExportFail {
            get {
                return ResourceManager.GetString("ExportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucessfully exported/uploaded {0} events..
        /// </summary>
        public static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Head to the following web site to manually upload your feedback:.
        /// </summary>
        public static string ExportSuccessLinkDescription {
            get {
                return ResourceManager.GetString("ExportSuccessLinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1/4: Loading.
        /// </summary>
        public static string FetchingEvents {
            get {
                return ResourceManager.GetString("FetchingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is nothing to export..
        /// </summary>
        public static string NothingToExport {
            get {
                return ResourceManager.GetString("NothingToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4/4: Saving.
        /// </summary>
        public static string PublishingEvents {
            get {
                return ResourceManager.GetString("PublishingEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Review Feedback.
        /// </summary>
        public static string review_link {
            get {
                return ResourceManager.GetString("review_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string userprofile_link {
            get {
                return ResourceManager.GetString("userprofile_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2/4: Writing - {0}%.
        /// </summary>
        public static string WritingEvents {
            get {
                return ResourceManager.GetString("WritingEvents", resourceCulture);
            }
        }
    }
}
