//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVE.RS.Commons.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaVE.RS.Commons.Properties.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keine Datei angegeben.
        /// </summary>
        internal static string NoFileGiven {
            get {
                return ResourceManager.GetString("NoFileGiven", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datei-Export fehlgeschlagen: {0}.
        /// </summary>
        internal static string PublishingFileFailed {
            get {
                return ResourceManager.GetString("PublishingFileFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Server ist nicht erreichbar (&quot;{0}&quot;).
        /// </summary>
        internal static string ServerRequestNotAvailable {
            get {
                return ResourceManager.GetString("ServerRequestNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Http-Upload erwartet Http- oder Https-Adresse.
        /// </summary>
        internal static string ServerRequestWrongScheme {
            get {
                return ResourceManager.GetString("ServerRequestWrongScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antwort des Servers enthält keine verwertbaren Informationen.
        /// </summary>
        internal static string ServerResponseEmpty {
            get {
                return ResourceManager.GetString("ServerResponseEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fehler bei der Anfrage an den Server &quot;{0}&quot;:
        ///{1}.
        /// </summary>
        internal static string ServerResponseFailure {
            get {
                return ResourceManager.GetString("ServerResponseFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inkompatible Antwort des Server.
        /// </summary>
        internal static string ServerResponseIncompatible {
            get {
                return ResourceManager.GetString("ServerResponseIncompatible", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Antwort des Servers entspricht nicht dem erwarteten Format:
        ///{0}.
        /// </summary>
        internal static string ServerResponseIncorrentFormat {
            get {
                return ResourceManager.GetString("ServerResponseIncorrentFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server meldet eine fehlerhafte Anfrage:
        ///{0}.
        /// </summary>
        internal static string ServerResponseRequestFailure {
            get {
                return ResourceManager.GetString("ServerResponseRequestFailure", resourceCulture);
            }
        }
    }
}
