//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVE.VS.FeedbackGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EnumLocalization {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumLocalization() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaVE.VS.FeedbackGenerator.Properties.EnumLocalization", typeof(EnumLocalization).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Self-taught / Autodidact.
        /// </summary>
        public static string Educations_Autodidact {
            get {
                return ResourceManager.GetString("Educations_Autodidact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bachelor.
        /// </summary>
        public static string Educations_Bachelor {
            get {
                return ResourceManager.GetString("Educations_Bachelor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Master.
        /// </summary>
        public static string Educations_Master {
            get {
                return ResourceManager.GetString("Educations_Master", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        public static string Educations_None {
            get {
                return ResourceManager.GetString("Educations_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ph.D..
        /// </summary>
        public static string Educations_PhD {
            get {
                return ResourceManager.GetString("Educations_PhD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Apprenticeship.
        /// </summary>
        public static string Educations_Training {
            get {
                return ResourceManager.GetString("Educations_Training", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Answer.
        /// </summary>
        public static string Educations_Unknown {
            get {
                return ResourceManager.GetString("Educations_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hobby Programmer.
        /// </summary>
        public static string Positions_HobbyProgrammer {
            get {
                return ResourceManager.GetString("Positions_HobbyProgrammer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Researcher (Academia).
        /// </summary>
        public static string Positions_ResearcherAcademic {
            get {
                return ResourceManager.GetString("Positions_ResearcherAcademic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Researcher (Industry).
        /// </summary>
        public static string Positions_ResearcherIndustry {
            get {
                return ResourceManager.GetString("Positions_ResearcherIndustry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Professional Software Engineer.
        /// </summary>
        public static string Positions_SoftwareEngineer {
            get {
                return ResourceManager.GetString("Positions_SoftwareEngineer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Student.
        /// </summary>
        public static string Positions_Student {
            get {
                return ResourceManager.GetString("Positions_Student", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Answer.
        /// </summary>
        public static string Positions_Unknown {
            get {
                return ResourceManager.GetString("Positions_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Localization.
        /// </summary>
        public static string TestEnum_ExistingKey {
            get {
                return ResourceManager.GetString("TestEnum_ExistingKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string YesNoUnknown_No {
            get {
                return ResourceManager.GetString("YesNoUnknown_No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Answer.
        /// </summary>
        public static string YesNoUnknown_Unknown {
            get {
                return ResourceManager.GetString("YesNoUnknown_Unknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string YesNoUnknown_Yes {
            get {
                return ResourceManager.GetString("YesNoUnknown_Yes", resourceCulture);
            }
        }
    }
}
