//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVE.VS.FeedbackGenerator.UserControls.ValidationRules {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ValidationErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ValidationErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaVE.VS.FeedbackGenerator.UserControls.ValidationRules.ValidationErrorMessages", typeof(ValidationErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The folder doesn&apos;t exist..
        /// </summary>
        internal static string FolderDoesntExist {
            get {
                return ResourceManager.GetString("FolderDoesntExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid web prefix..
        /// </summary>
        internal static string GeneralOptions_InvalidPrefix {
            get {
                return ResourceManager.GetString("GeneralOptions_InvalidPrefix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid URL..
        /// </summary>
        internal static string GeneralOptions_InvalidUploadURL {
            get {
                return ResourceManager.GetString("GeneralOptions_InvalidUploadURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No valid remote source. Please enter a local path or URI..
        /// </summary>
        internal static string UsageModelsOptions_InvalidUri {
            get {
                return ResourceManager.GetString("UsageModelsOptions_InvalidUri", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Couldn&apos;t find file &apos;index.json.gz&apos;..
        /// </summary>
        internal static string UsageModelsOptions_NoIndexFile {
            get {
                return ResourceManager.GetString("UsageModelsOptions_NoIndexFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The given URI Scheme is not supported. Please enter a file, http or https URI..
        /// </summary>
        internal static string UsageModelsOptions_UriSchemeNotSupported {
            get {
                return ResourceManager.GetString("UsageModelsOptions_UriSchemeNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter a valid mail address..
        /// </summary>
        internal static string UserProfile_InvalidMail {
            get {
                return ResourceManager.GetString("UserProfile_InvalidMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This field cannot be empty..
        /// </summary>
        internal static string ValueIsEmptyString {
            get {
                return ResourceManager.GetString("ValueIsEmptyString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is null..
        /// </summary>
        internal static string ValueIsNull {
            get {
                return ResourceManager.GetString("ValueIsNull", resourceCulture);
            }
        }
    }
}
