//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVE.VS.FeedbackGenerator.UserControls.UploadWizard {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UploadWizardMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UploadWizardMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaVE.VS.FeedbackGenerator.UserControls.UploadWizard.UploadWizardMessages", typeof(UploadWizardMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymization Settings.
        /// </summary>
        public static string AnonymizationWindow_Title {
            get {
                return ResourceManager.GetString("AnonymizationWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you very much for being an active user of the KaVE project and for providing feedback about your usage of Visual Studio.
        ///
        ///You have two options now to provide your feedback:
        ///- ZIP-Export: the feedback is locally exported to a compressed file. You can review the contents of the file before you manually upload it to the URL that is presented to you after the successful export.
        ///- Direct upload: your feedback is directly send to our server. It is more convenient, because you don&apos;t need to manually uplo [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment (optional).
        /// </summary>
        public static string Label_CommentHeader {
            get {
                return ResourceManager.GetString("Label_CommentHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t participate.
        /// </summary>
        public static string NoParticipationButton_Content {
            get {
                return ResourceManager.GetString("NoParticipationButton_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Providing Feedback.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We would like to learn more about our users, please help us by answering several simple questions about yourself. You can leave out any question, if you do not want to answer it. Your answers will be attached to your uploaded feedback.
        ///
        ///Thank You!.
        /// </summary>
        public static string UserProfileReminderWindow_Text {
            get {
                return ResourceManager.GetString("UserProfileReminderWindow_Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile.
        /// </summary>
        public static string UserProfileReminderWindow_Title {
            get {
                return ResourceManager.GetString("UserProfileReminderWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Profile Settings.
        /// </summary>
        public static string UserProfileWindow_Title {
            get {
                return ResourceManager.GetString("UserProfileWindow_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string WindowOkButton_Content {
            get {
                return ResourceManager.GetString("WindowOkButton_Content", resourceCulture);
            }
        }
    }
}
