//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.5.3-SNAPSHOT
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from C:\Users\Jonas\Documents\Visual Studio 2013\Projects\Grammar\Grammar\Model\Names\CSharp\Parser\TypeNaming.g4 by ANTLR 4.5.3-SNAPSHOT

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

namespace KaVE.Commons.Model.Names.CSharp.Parser {

/**
 * Copyright 2016 Sebastian Proksch
 * 
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 * 
 *    http://www.apache.org/licenses/LICENSE-2.0
 * 
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

using Antlr4.Runtime;
using Antlr4.Runtime.Atn;
using Antlr4.Runtime.Misc;
using Antlr4.Runtime.Tree;
using System.Collections.Generic;
using DFA = Antlr4.Runtime.Dfa.DFA;

[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.5.3-SNAPSHOT")]
[System.CLSCompliant(false)]
public partial class TypeNamingParser : Parser {
	public const int
		T__0=1, T__1=2, T__2=3, T__3=4, T__4=5, T__5=6, T__6=7, T__7=8, T__8=9, 
		T__9=10, T__10=11, T__11=12, T__12=13, T__13=14, T__14=15, T__15=16, T__16=17, 
		T__17=18, T__18=19, T__19=20, T__20=21, T__21=22, T__22=23, T__23=24, 
		T__24=25, T__25=26, UNKNOWN=27, POSNUM=28, LETTER=29, SIGN=30, WS=31, 
		EOL=32;
	public const int
		RULE_typeEOL = 0, RULE_methodEOL = 1, RULE_namespaceEOL = 2, RULE_assemblyEOL = 3, 
		RULE_parameterNameEOL = 4, RULE_type = 5, RULE_typeParameter = 6, RULE_notTypeParameter = 7, 
		RULE_regularType = 8, RULE_delegateType = 9, RULE_arrayType = 10, RULE_nestedType = 11, 
		RULE_nestedTypeName = 12, RULE_resolvedType = 13, RULE_namespace = 14, 
		RULE_typeName = 15, RULE_possiblyGenericTypeName = 16, RULE_enumTypeName = 17, 
		RULE_interfaceTypeName = 18, RULE_structTypeName = 19, RULE_simpleTypeName = 20, 
		RULE_genericTypePart = 21, RULE_genericParam = 22, RULE_assembly = 23, 
		RULE_regularAssembly = 24, RULE_assemblyVersion = 25, RULE_method = 26, 
		RULE_regularMethod = 27, RULE_methodParameters = 28, RULE_nonStaticCtor = 29, 
		RULE_staticCctor = 30, RULE_customMethod = 31, RULE_formalParam = 32, 
		RULE_parameterModifier = 33, RULE_staticModifier = 34, RULE_paramsModifier = 35, 
		RULE_optsModifier = 36, RULE_refModifier = 37, RULE_outModifier = 38, 
		RULE_extensionModifier = 39, RULE_id = 40, RULE_num = 41;
	public static readonly string[] ruleNames = {
		"typeEOL", "methodEOL", "namespaceEOL", "assemblyEOL", "parameterNameEOL", 
		"type", "typeParameter", "notTypeParameter", "regularType", "delegateType", 
		"arrayType", "nestedType", "nestedTypeName", "resolvedType", "namespace", 
		"typeName", "possiblyGenericTypeName", "enumTypeName", "interfaceTypeName", 
		"structTypeName", "simpleTypeName", "genericTypePart", "genericParam", 
		"assembly", "regularAssembly", "assemblyVersion", "method", "regularMethod", 
		"methodParameters", "nonStaticCtor", "staticCctor", "customMethod", "formalParam", 
		"parameterModifier", "staticModifier", "paramsModifier", "optsModifier", 
		"refModifier", "outModifier", "extensionModifier", "id", "num"
	};

	private static readonly string[] _LiteralNames = {
		null, "'->'", "','", "'d:'", "'arr('", "'):'", "'n:'", "'+'", "'.'", "'e:'", 
		"'i:'", "'s:'", "'''", "'['", "']'", "'('", "')'", "']..ctor'", "']..cctor'", 
		"'].'", "'static'", "'params '", "'opt '", "'ref '", "'out '", "'this '", 
		"'0'", "'?'", null, null, null, null, "'\n'"
	};
	private static readonly string[] _SymbolicNames = {
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, null, null, null, null, null, null, null, null, null, 
		null, null, null, "UNKNOWN", "POSNUM", "LETTER", "SIGN", "WS", "EOL"
	};
	public static readonly IVocabulary DefaultVocabulary = new Vocabulary(_LiteralNames, _SymbolicNames);

	[System.Obsolete("Use Vocabulary instead.")]
	public static readonly string[] tokenNames = GenerateTokenNames(DefaultVocabulary, _SymbolicNames.Length);

	private static string[] GenerateTokenNames(IVocabulary vocabulary, int length) {
		string[] tokenNames = new string[length];
		for (int i = 0; i < tokenNames.Length; i++) {
			tokenNames[i] = vocabulary.GetLiteralName(i);
			if (tokenNames[i] == null) {
				tokenNames[i] = vocabulary.GetSymbolicName(i);
			}

			if (tokenNames[i] == null) {
				tokenNames[i] = "<INVALID>";
			}
		}

		return tokenNames;
	}

	[System.Obsolete]
	public override string[] TokenNames
	{
		get
		{
			return tokenNames;
		}
	}

	[NotNull]
	public override IVocabulary Vocabulary
	{
		get
		{
			return DefaultVocabulary;
		}
	}

	public override string GrammarFileName { get { return "TypeNaming.g4"; } }

	public override string[] RuleNames { get { return ruleNames; } }

	public override string SerializedAtn { get { return _serializedATN; } }

	public TypeNamingParser(ITokenStream input)
		: base(input)
	{
		_interp = new ParserATNSimulator(this,_ATN);
	}
	public partial class TypeEOLContext : ParserRuleContext {
		public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public ITerminalNode EOL() { return GetToken(TypeNamingParser.EOL, 0); }
		public TypeEOLContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeEOL; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterTypeEOL(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitTypeEOL(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeEOL(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeEOLContext typeEOL() {
		TypeEOLContext _localctx = new TypeEOLContext(_ctx, State);
		EnterRule(_localctx, 0, RULE_typeEOL);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 84; type();
			State = 85; Match(EOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MethodEOLContext : ParserRuleContext {
		public MethodContext method() {
			return GetRuleContext<MethodContext>(0);
		}
		public ITerminalNode EOL() { return GetToken(TypeNamingParser.EOL, 0); }
		public MethodEOLContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_methodEOL; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterMethodEOL(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitMethodEOL(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMethodEOL(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MethodEOLContext methodEOL() {
		MethodEOLContext _localctx = new MethodEOLContext(_ctx, State);
		EnterRule(_localctx, 2, RULE_methodEOL);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 87; method();
			State = 88; Match(EOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NamespaceEOLContext : ParserRuleContext {
		public NamespaceContext @namespace() {
			return GetRuleContext<NamespaceContext>(0);
		}
		public ITerminalNode EOL() { return GetToken(TypeNamingParser.EOL, 0); }
		public NamespaceEOLContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_namespaceEOL; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterNamespaceEOL(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitNamespaceEOL(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNamespaceEOL(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NamespaceEOLContext namespaceEOL() {
		NamespaceEOLContext _localctx = new NamespaceEOLContext(_ctx, State);
		EnterRule(_localctx, 4, RULE_namespaceEOL);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 90; @namespace();
			State = 91; Match(EOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssemblyEOLContext : ParserRuleContext {
		public AssemblyContext assembly() {
			return GetRuleContext<AssemblyContext>(0);
		}
		public ITerminalNode EOL() { return GetToken(TypeNamingParser.EOL, 0); }
		public AssemblyEOLContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assemblyEOL; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterAssemblyEOL(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitAssemblyEOL(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssemblyEOL(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssemblyEOLContext assemblyEOL() {
		AssemblyEOLContext _localctx = new AssemblyEOLContext(_ctx, State);
		EnterRule(_localctx, 6, RULE_assemblyEOL);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 93; assembly();
			State = 94; Match(EOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterNameEOLContext : ParserRuleContext {
		public FormalParamContext formalParam() {
			return GetRuleContext<FormalParamContext>(0);
		}
		public ITerminalNode EOL() { return GetToken(TypeNamingParser.EOL, 0); }
		public ParameterNameEOLContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameterNameEOL; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterParameterNameEOL(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitParameterNameEOL(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParameterNameEOL(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParameterNameEOLContext parameterNameEOL() {
		ParameterNameEOLContext _localctx = new ParameterNameEOLContext(_ctx, State);
		EnterRule(_localctx, 8, RULE_parameterNameEOL);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 96; formalParam();
			State = 97; Match(EOL);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeContext : ParserRuleContext {
		public ITerminalNode UNKNOWN() { return GetToken(TypeNamingParser.UNKNOWN, 0); }
		public TypeParameterContext typeParameter() {
			return GetRuleContext<TypeParameterContext>(0);
		}
		public RegularTypeContext regularType() {
			return GetRuleContext<RegularTypeContext>(0);
		}
		public DelegateTypeContext delegateType() {
			return GetRuleContext<DelegateTypeContext>(0);
		}
		public ArrayTypeContext arrayType() {
			return GetRuleContext<ArrayTypeContext>(0);
		}
		public TypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_type; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterType(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitType(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeContext type() {
		TypeContext _localctx = new TypeContext(_ctx, State);
		EnterRule(_localctx, 10, RULE_type);
		try {
			State = 104;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,0,_ctx) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 99; Match(UNKNOWN);
				}
				break;

			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 100; typeParameter();
				}
				break;

			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 101; regularType();
				}
				break;

			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 102; delegateType();
				}
				break;

			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 103; arrayType();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeParameterContext : ParserRuleContext {
		public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		public NotTypeParameterContext notTypeParameter() {
			return GetRuleContext<NotTypeParameterContext>(0);
		}
		public ITerminalNode[] WS() { return GetTokens(TypeNamingParser.WS); }
		public ITerminalNode WS(int i) {
			return GetToken(TypeNamingParser.WS, i);
		}
		public TypeParameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeParameter; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterTypeParameter(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitTypeParameter(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeParameter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeParameterContext typeParameter() {
		TypeParameterContext _localctx = new TypeParameterContext(_ctx, State);
		EnterRule(_localctx, 12, RULE_typeParameter);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 106; id();
			State = 115;
			_la = _input.La(1);
			if (_la==T__0 || _la==WS) {
				{
				State = 108;
				_la = _input.La(1);
				if (_la==WS) {
					{
					State = 107; Match(WS);
					}
				}

				State = 110; Match(T__0);
				State = 112;
				_la = _input.La(1);
				if (_la==WS) {
					{
					State = 111; Match(WS);
					}
				}

				State = 114; notTypeParameter();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NotTypeParameterContext : ParserRuleContext {
		public RegularTypeContext regularType() {
			return GetRuleContext<RegularTypeContext>(0);
		}
		public DelegateTypeContext delegateType() {
			return GetRuleContext<DelegateTypeContext>(0);
		}
		public ArrayTypeContext arrayType() {
			return GetRuleContext<ArrayTypeContext>(0);
		}
		public ITerminalNode UNKNOWN() { return GetToken(TypeNamingParser.UNKNOWN, 0); }
		public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		public NotTypeParameterContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_notTypeParameter; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterNotTypeParameter(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitNotTypeParameter(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNotTypeParameter(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NotTypeParameterContext notTypeParameter() {
		NotTypeParameterContext _localctx = new NotTypeParameterContext(_ctx, State);
		EnterRule(_localctx, 14, RULE_notTypeParameter);
		try {
			State = 122;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,4,_ctx) ) {
			case 1:
				EnterOuterAlt(_localctx, 1);
				{
				State = 117; regularType();
				}
				break;

			case 2:
				EnterOuterAlt(_localctx, 2);
				{
				State = 118; delegateType();
				}
				break;

			case 3:
				EnterOuterAlt(_localctx, 3);
				{
				State = 119; arrayType();
				}
				break;

			case 4:
				EnterOuterAlt(_localctx, 4);
				{
				State = 120; Match(UNKNOWN);
				}
				break;

			case 5:
				EnterOuterAlt(_localctx, 5);
				{
				State = 121; id();
				}
				break;
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RegularTypeContext : ParserRuleContext {
		public AssemblyContext assembly() {
			return GetRuleContext<AssemblyContext>(0);
		}
		public ResolvedTypeContext resolvedType() {
			return GetRuleContext<ResolvedTypeContext>(0);
		}
		public NestedTypeContext nestedType() {
			return GetRuleContext<NestedTypeContext>(0);
		}
		public ITerminalNode WS() { return GetToken(TypeNamingParser.WS, 0); }
		public RegularTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_regularType; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterRegularType(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitRegularType(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRegularType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RegularTypeContext regularType() {
		RegularTypeContext _localctx = new RegularTypeContext(_ctx, State);
		EnterRule(_localctx, 16, RULE_regularType);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 126;
			switch (_input.La(1)) {
			case T__8:
			case T__9:
			case T__10:
			case LETTER:
				{
				State = 124; resolvedType();
				}
				break;
			case T__5:
				{
				State = 125; nestedType();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 128; Match(T__1);
			State = 130;
			_la = _input.La(1);
			if (_la==WS) {
				{
				State = 129; Match(WS);
				}
			}

			State = 132; assembly();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class DelegateTypeContext : ParserRuleContext {
		public MethodContext method() {
			return GetRuleContext<MethodContext>(0);
		}
		public DelegateTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_delegateType; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterDelegateType(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitDelegateType(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitDelegateType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public DelegateTypeContext delegateType() {
		DelegateTypeContext _localctx = new DelegateTypeContext(_ctx, State);
		EnterRule(_localctx, 18, RULE_delegateType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 134; Match(T__2);
			State = 135; method();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ArrayTypeContext : ParserRuleContext {
		public ITerminalNode POSNUM() { return GetToken(TypeNamingParser.POSNUM, 0); }
		public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public ArrayTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_arrayType; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterArrayType(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitArrayType(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitArrayType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ArrayTypeContext arrayType() {
		ArrayTypeContext _localctx = new ArrayTypeContext(_ctx, State);
		EnterRule(_localctx, 20, RULE_arrayType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 137; Match(T__3);
			State = 138; Match(POSNUM);
			State = 139; Match(T__4);
			State = 140; type();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NestedTypeContext : ParserRuleContext {
		public NestedTypeNameContext nestedTypeName() {
			return GetRuleContext<NestedTypeNameContext>(0);
		}
		public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		public NestedTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nestedType; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterNestedType(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitNestedType(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNestedType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NestedTypeContext nestedType() {
		NestedTypeContext _localctx = new NestedTypeContext(_ctx, State);
		EnterRule(_localctx, 22, RULE_nestedType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 142; Match(T__5);
			State = 143; nestedTypeName();
			State = 144; Match(T__6);
			State = 145; typeName();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NestedTypeNameContext : ParserRuleContext {
		public NestedTypeContext nestedType() {
			return GetRuleContext<NestedTypeContext>(0);
		}
		public ResolvedTypeContext resolvedType() {
			return GetRuleContext<ResolvedTypeContext>(0);
		}
		public NestedTypeNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nestedTypeName; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterNestedTypeName(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitNestedTypeName(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNestedTypeName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NestedTypeNameContext nestedTypeName() {
		NestedTypeNameContext _localctx = new NestedTypeNameContext(_ctx, State);
		EnterRule(_localctx, 24, RULE_nestedTypeName);
		try {
			State = 149;
			switch (_input.La(1)) {
			case T__5:
				EnterOuterAlt(_localctx, 1);
				{
				State = 147; nestedType();
				}
				break;
			case T__8:
			case T__9:
			case T__10:
			case LETTER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 148; resolvedType();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ResolvedTypeContext : ParserRuleContext {
		public TypeNameContext typeName() {
			return GetRuleContext<TypeNameContext>(0);
		}
		public NamespaceContext @namespace() {
			return GetRuleContext<NamespaceContext>(0);
		}
		public ResolvedTypeContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_resolvedType; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterResolvedType(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitResolvedType(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitResolvedType(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ResolvedTypeContext resolvedType() {
		ResolvedTypeContext _localctx = new ResolvedTypeContext(_ctx, State);
		EnterRule(_localctx, 26, RULE_resolvedType);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 152;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,8,_ctx) ) {
			case 1:
				{
				State = 151; @namespace();
				}
				break;
			}
			State = 154; typeName();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NamespaceContext : ParserRuleContext {
		public IdContext[] id() {
			return GetRuleContexts<IdContext>();
		}
		public IdContext id(int i) {
			return GetRuleContext<IdContext>(i);
		}
		public NamespaceContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_namespace; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterNamespace(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitNamespace(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNamespace(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NamespaceContext @namespace() {
		NamespaceContext _localctx = new NamespaceContext(_ctx, State);
		EnterRule(_localctx, 28, RULE_namespace);
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 159;
			_errHandler.Sync(this);
			_alt = 1;
			do {
				switch (_alt) {
				case 1:
					{
					{
					State = 156; id();
					State = 157; Match(T__7);
					}
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				State = 161;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,9,_ctx);
			} while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber );
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class TypeNameContext : ParserRuleContext {
		public EnumTypeNameContext enumTypeName() {
			return GetRuleContext<EnumTypeNameContext>(0);
		}
		public PossiblyGenericTypeNameContext possiblyGenericTypeName() {
			return GetRuleContext<PossiblyGenericTypeNameContext>(0);
		}
		public TypeNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_typeName; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterTypeName(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitTypeName(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitTypeName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public TypeNameContext typeName() {
		TypeNameContext _localctx = new TypeNameContext(_ctx, State);
		EnterRule(_localctx, 30, RULE_typeName);
		try {
			State = 165;
			switch (_input.La(1)) {
			case T__8:
				EnterOuterAlt(_localctx, 1);
				{
				State = 163; enumTypeName();
				}
				break;
			case T__9:
			case T__10:
			case LETTER:
				EnterOuterAlt(_localctx, 2);
				{
				State = 164; possiblyGenericTypeName();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class PossiblyGenericTypeNameContext : ParserRuleContext {
		public InterfaceTypeNameContext interfaceTypeName() {
			return GetRuleContext<InterfaceTypeNameContext>(0);
		}
		public StructTypeNameContext structTypeName() {
			return GetRuleContext<StructTypeNameContext>(0);
		}
		public SimpleTypeNameContext simpleTypeName() {
			return GetRuleContext<SimpleTypeNameContext>(0);
		}
		public GenericTypePartContext genericTypePart() {
			return GetRuleContext<GenericTypePartContext>(0);
		}
		public PossiblyGenericTypeNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_possiblyGenericTypeName; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterPossiblyGenericTypeName(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitPossiblyGenericTypeName(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitPossiblyGenericTypeName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public PossiblyGenericTypeNameContext possiblyGenericTypeName() {
		PossiblyGenericTypeNameContext _localctx = new PossiblyGenericTypeNameContext(_ctx, State);
		EnterRule(_localctx, 32, RULE_possiblyGenericTypeName);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 170;
			switch (_input.La(1)) {
			case T__9:
				{
				State = 167; interfaceTypeName();
				}
				break;
			case T__10:
				{
				State = 168; structTypeName();
				}
				break;
			case LETTER:
				{
				State = 169; simpleTypeName();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
			State = 173;
			_la = _input.La(1);
			if (_la==T__11) {
				{
				State = 172; genericTypePart();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class EnumTypeNameContext : ParserRuleContext {
		public SimpleTypeNameContext simpleTypeName() {
			return GetRuleContext<SimpleTypeNameContext>(0);
		}
		public EnumTypeNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_enumTypeName; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterEnumTypeName(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitEnumTypeName(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitEnumTypeName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public EnumTypeNameContext enumTypeName() {
		EnumTypeNameContext _localctx = new EnumTypeNameContext(_ctx, State);
		EnterRule(_localctx, 34, RULE_enumTypeName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 175; Match(T__8);
			State = 176; simpleTypeName();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class InterfaceTypeNameContext : ParserRuleContext {
		public SimpleTypeNameContext simpleTypeName() {
			return GetRuleContext<SimpleTypeNameContext>(0);
		}
		public InterfaceTypeNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_interfaceTypeName; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterInterfaceTypeName(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitInterfaceTypeName(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitInterfaceTypeName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public InterfaceTypeNameContext interfaceTypeName() {
		InterfaceTypeNameContext _localctx = new InterfaceTypeNameContext(_ctx, State);
		EnterRule(_localctx, 36, RULE_interfaceTypeName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 178; Match(T__9);
			State = 179; simpleTypeName();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StructTypeNameContext : ParserRuleContext {
		public SimpleTypeNameContext simpleTypeName() {
			return GetRuleContext<SimpleTypeNameContext>(0);
		}
		public StructTypeNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_structTypeName; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterStructTypeName(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitStructTypeName(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStructTypeName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StructTypeNameContext structTypeName() {
		StructTypeNameContext _localctx = new StructTypeNameContext(_ctx, State);
		EnterRule(_localctx, 38, RULE_structTypeName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 181; Match(T__10);
			State = 182; simpleTypeName();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class SimpleTypeNameContext : ParserRuleContext {
		public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		public SimpleTypeNameContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_simpleTypeName; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterSimpleTypeName(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitSimpleTypeName(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitSimpleTypeName(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public SimpleTypeNameContext simpleTypeName() {
		SimpleTypeNameContext _localctx = new SimpleTypeNameContext(_ctx, State);
		EnterRule(_localctx, 40, RULE_simpleTypeName);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 184; id();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GenericTypePartContext : ParserRuleContext {
		public ITerminalNode POSNUM() { return GetToken(TypeNamingParser.POSNUM, 0); }
		public GenericParamContext[] genericParam() {
			return GetRuleContexts<GenericParamContext>();
		}
		public GenericParamContext genericParam(int i) {
			return GetRuleContext<GenericParamContext>(i);
		}
		public GenericTypePartContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_genericTypePart; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterGenericTypePart(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitGenericTypePart(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGenericTypePart(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GenericTypePartContext genericTypePart() {
		GenericTypePartContext _localctx = new GenericTypePartContext(_ctx, State);
		EnterRule(_localctx, 42, RULE_genericTypePart);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 186; Match(T__11);
			State = 187; Match(POSNUM);
			State = 188; Match(T__12);
			State = 189; genericParam();
			State = 194;
			_errHandler.Sync(this);
			_la = _input.La(1);
			while (_la==T__1) {
				{
				{
				State = 190; Match(T__1);
				State = 191; genericParam();
				}
				}
				State = 196;
				_errHandler.Sync(this);
				_la = _input.La(1);
			}
			State = 197; Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class GenericParamContext : ParserRuleContext {
		public TypeParameterContext typeParameter() {
			return GetRuleContext<TypeParameterContext>(0);
		}
		public GenericParamContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_genericParam; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterGenericParam(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitGenericParam(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitGenericParam(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public GenericParamContext genericParam() {
		GenericParamContext _localctx = new GenericParamContext(_ctx, State);
		EnterRule(_localctx, 44, RULE_genericParam);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 199; Match(T__12);
			State = 200; typeParameter();
			State = 201; Match(T__13);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssemblyContext : ParserRuleContext {
		public RegularAssemblyContext regularAssembly() {
			return GetRuleContext<RegularAssemblyContext>(0);
		}
		public ITerminalNode UNKNOWN() { return GetToken(TypeNamingParser.UNKNOWN, 0); }
		public AssemblyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assembly; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterAssembly(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitAssembly(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssembly(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssemblyContext assembly() {
		AssemblyContext _localctx = new AssemblyContext(_ctx, State);
		EnterRule(_localctx, 46, RULE_assembly);
		try {
			State = 205;
			switch (_input.La(1)) {
			case LETTER:
				EnterOuterAlt(_localctx, 1);
				{
				State = 203; regularAssembly();
				}
				break;
			case UNKNOWN:
				EnterOuterAlt(_localctx, 2);
				{
				State = 204; Match(UNKNOWN);
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RegularAssemblyContext : ParserRuleContext {
		public IdContext[] id() {
			return GetRuleContexts<IdContext>();
		}
		public IdContext id(int i) {
			return GetRuleContext<IdContext>(i);
		}
		public AssemblyVersionContext assemblyVersion() {
			return GetRuleContext<AssemblyVersionContext>(0);
		}
		public ITerminalNode WS() { return GetToken(TypeNamingParser.WS, 0); }
		public RegularAssemblyContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_regularAssembly; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterRegularAssembly(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitRegularAssembly(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRegularAssembly(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RegularAssemblyContext regularAssembly() {
		RegularAssemblyContext _localctx = new RegularAssemblyContext(_ctx, State);
		EnterRule(_localctx, 48, RULE_regularAssembly);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 212;
			_errHandler.Sync(this);
			_alt = Interpreter.AdaptivePredict(_input,15,_ctx);
			while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
				if ( _alt==1 ) {
					{
					{
					State = 207; id();
					State = 208; Match(T__7);
					}
					} 
				}
				State = 214;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,15,_ctx);
			}
			State = 215; id();
			State = 221;
			_la = _input.La(1);
			if (_la==T__1) {
				{
				State = 216; Match(T__1);
				State = 218;
				_la = _input.La(1);
				if (_la==WS) {
					{
					State = 217; Match(WS);
					}
				}

				State = 220; assemblyVersion();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class AssemblyVersionContext : ParserRuleContext {
		public NumContext[] num() {
			return GetRuleContexts<NumContext>();
		}
		public NumContext num(int i) {
			return GetRuleContext<NumContext>(i);
		}
		public AssemblyVersionContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_assemblyVersion; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterAssemblyVersion(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitAssemblyVersion(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitAssemblyVersion(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public AssemblyVersionContext assemblyVersion() {
		AssemblyVersionContext _localctx = new AssemblyVersionContext(_ctx, State);
		EnterRule(_localctx, 50, RULE_assemblyVersion);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 223; num();
			State = 224; Match(T__7);
			State = 225; num();
			State = 226; Match(T__7);
			State = 227; num();
			State = 228; Match(T__7);
			State = 229; num();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MethodContext : ParserRuleContext {
		public ITerminalNode UNKNOWN() { return GetToken(TypeNamingParser.UNKNOWN, 0); }
		public RegularMethodContext regularMethod() {
			return GetRuleContext<RegularMethodContext>(0);
		}
		public MethodContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_method; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterMethod(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitMethod(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMethod(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MethodContext method() {
		MethodContext _localctx = new MethodContext(_ctx, State);
		EnterRule(_localctx, 52, RULE_method);
		try {
			State = 233;
			switch (_input.La(1)) {
			case UNKNOWN:
				EnterOuterAlt(_localctx, 1);
				{
				State = 231; Match(UNKNOWN);
				}
				break;
			case T__12:
			case T__19:
			case WS:
				EnterOuterAlt(_localctx, 2);
				{
				State = 232; regularMethod();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RegularMethodContext : ParserRuleContext {
		public MethodParametersContext methodParameters() {
			return GetRuleContext<MethodParametersContext>(0);
		}
		public NonStaticCtorContext nonStaticCtor() {
			return GetRuleContext<NonStaticCtorContext>(0);
		}
		public StaticCctorContext staticCctor() {
			return GetRuleContext<StaticCctorContext>(0);
		}
		public CustomMethodContext customMethod() {
			return GetRuleContext<CustomMethodContext>(0);
		}
		public RegularMethodContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_regularMethod; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterRegularMethod(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitRegularMethod(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRegularMethod(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RegularMethodContext regularMethod() {
		RegularMethodContext _localctx = new RegularMethodContext(_ctx, State);
		EnterRule(_localctx, 54, RULE_regularMethod);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 238;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,19,_ctx) ) {
			case 1:
				{
				State = 235; nonStaticCtor();
				}
				break;

			case 2:
				{
				State = 236; staticCctor();
				}
				break;

			case 3:
				{
				State = 237; customMethod();
				}
				break;
			}
			State = 240; methodParameters();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class MethodParametersContext : ParserRuleContext {
		public ITerminalNode[] WS() { return GetTokens(TypeNamingParser.WS); }
		public ITerminalNode WS(int i) {
			return GetToken(TypeNamingParser.WS, i);
		}
		public FormalParamContext[] formalParam() {
			return GetRuleContexts<FormalParamContext>();
		}
		public FormalParamContext formalParam(int i) {
			return GetRuleContext<FormalParamContext>(i);
		}
		public MethodParametersContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_methodParameters; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterMethodParameters(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitMethodParameters(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitMethodParameters(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public MethodParametersContext methodParameters() {
		MethodParametersContext _localctx = new MethodParametersContext(_ctx, State);
		EnterRule(_localctx, 56, RULE_methodParameters);
		int _la;
		try {
			int _alt;
			EnterOuterAlt(_localctx, 1);
			{
			State = 242; Match(T__14);
			State = 244;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,20,_ctx) ) {
			case 1:
				{
				State = 243; Match(WS);
				}
				break;
			}
			State = 260;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,24,_ctx) ) {
			case 1:
				{
				State = 246; formalParam();
				State = 257;
				_errHandler.Sync(this);
				_alt = Interpreter.AdaptivePredict(_input,23,_ctx);
				while ( _alt!=2 && _alt!=global::Antlr4.Runtime.Atn.ATN.InvalidAltNumber ) {
					if ( _alt==1 ) {
						{
						{
						State = 248;
						_la = _input.La(1);
						if (_la==WS) {
							{
							State = 247; Match(WS);
							}
						}

						State = 250; Match(T__1);
						State = 252;
						_errHandler.Sync(this);
						switch ( Interpreter.AdaptivePredict(_input,22,_ctx) ) {
						case 1:
							{
							State = 251; Match(WS);
							}
							break;
						}
						State = 254; formalParam();
						}
						} 
					}
					State = 259;
					_errHandler.Sync(this);
					_alt = Interpreter.AdaptivePredict(_input,23,_ctx);
				}
				}
				break;
			}
			State = 263;
			_la = _input.La(1);
			if (_la==WS) {
				{
				State = 262; Match(WS);
				}
			}

			State = 265; Match(T__15);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NonStaticCtorContext : ParserRuleContext {
		public ITerminalNode UNKNOWN() { return GetToken(TypeNamingParser.UNKNOWN, 0); }
		public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public ITerminalNode[] WS() { return GetTokens(TypeNamingParser.WS); }
		public ITerminalNode WS(int i) {
			return GetToken(TypeNamingParser.WS, i);
		}
		public NonStaticCtorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_nonStaticCtor; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterNonStaticCtor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitNonStaticCtor(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNonStaticCtor(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NonStaticCtorContext nonStaticCtor() {
		NonStaticCtorContext _localctx = new NonStaticCtorContext(_ctx, State);
		EnterRule(_localctx, 58, RULE_nonStaticCtor);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 268;
			_la = _input.La(1);
			if (_la==WS) {
				{
				State = 267; Match(WS);
				}
			}

			State = 270; Match(T__12);
			State = 271; Match(UNKNOWN);
			State = 272; Match(T__13);
			State = 274;
			_la = _input.La(1);
			if (_la==WS) {
				{
				State = 273; Match(WS);
				}
			}

			State = 276; Match(T__12);
			State = 277; type();
			State = 278; Match(T__16);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StaticCctorContext : ParserRuleContext {
		public StaticModifierContext staticModifier() {
			return GetRuleContext<StaticModifierContext>(0);
		}
		public ITerminalNode UNKNOWN() { return GetToken(TypeNamingParser.UNKNOWN, 0); }
		public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public ITerminalNode[] WS() { return GetTokens(TypeNamingParser.WS); }
		public ITerminalNode WS(int i) {
			return GetToken(TypeNamingParser.WS, i);
		}
		public StaticCctorContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_staticCctor; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterStaticCctor(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitStaticCctor(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStaticCctor(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StaticCctorContext staticCctor() {
		StaticCctorContext _localctx = new StaticCctorContext(_ctx, State);
		EnterRule(_localctx, 60, RULE_staticCctor);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 280; staticModifier();
			State = 282;
			_la = _input.La(1);
			if (_la==WS) {
				{
				State = 281; Match(WS);
				}
			}

			State = 284; Match(T__12);
			State = 285; Match(UNKNOWN);
			State = 286; Match(T__13);
			State = 288;
			_la = _input.La(1);
			if (_la==WS) {
				{
				State = 287; Match(WS);
				}
			}

			State = 290; Match(T__12);
			State = 291; type();
			State = 292; Match(T__17);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class CustomMethodContext : ParserRuleContext {
		public TypeContext[] type() {
			return GetRuleContexts<TypeContext>();
		}
		public TypeContext type(int i) {
			return GetRuleContext<TypeContext>(i);
		}
		public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		public StaticModifierContext staticModifier() {
			return GetRuleContext<StaticModifierContext>(0);
		}
		public ITerminalNode[] WS() { return GetTokens(TypeNamingParser.WS); }
		public ITerminalNode WS(int i) {
			return GetToken(TypeNamingParser.WS, i);
		}
		public GenericTypePartContext genericTypePart() {
			return GetRuleContext<GenericTypePartContext>(0);
		}
		public CustomMethodContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_customMethod; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterCustomMethod(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitCustomMethod(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitCustomMethod(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public CustomMethodContext customMethod() {
		CustomMethodContext _localctx = new CustomMethodContext(_ctx, State);
		EnterRule(_localctx, 62, RULE_customMethod);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 295;
			_la = _input.La(1);
			if (_la==T__19) {
				{
				State = 294; staticModifier();
				}
			}

			State = 298;
			_la = _input.La(1);
			if (_la==WS) {
				{
				State = 297; Match(WS);
				}
			}

			State = 300; Match(T__12);
			State = 301; type();
			State = 302; Match(T__13);
			State = 304;
			_la = _input.La(1);
			if (_la==WS) {
				{
				State = 303; Match(WS);
				}
			}

			State = 306; Match(T__12);
			State = 307; type();
			State = 308; Match(T__18);
			State = 309; id();
			State = 311;
			_la = _input.La(1);
			if (_la==T__11) {
				{
				State = 310; genericTypePart();
				}
			}

			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class FormalParamContext : ParserRuleContext {
		public TypeContext type() {
			return GetRuleContext<TypeContext>(0);
		}
		public IdContext id() {
			return GetRuleContext<IdContext>(0);
		}
		public ParameterModifierContext parameterModifier() {
			return GetRuleContext<ParameterModifierContext>(0);
		}
		public ITerminalNode[] WS() { return GetTokens(TypeNamingParser.WS); }
		public ITerminalNode WS(int i) {
			return GetToken(TypeNamingParser.WS, i);
		}
		public FormalParamContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_formalParam; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterFormalParam(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitFormalParam(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitFormalParam(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public FormalParamContext formalParam() {
		FormalParamContext _localctx = new FormalParamContext(_ctx, State);
		EnterRule(_localctx, 64, RULE_formalParam);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 317;
			_errHandler.Sync(this);
			switch ( Interpreter.AdaptivePredict(_input,35,_ctx) ) {
			case 1:
				{
				State = 314;
				_la = _input.La(1);
				if (_la==WS) {
					{
					State = 313; Match(WS);
					}
				}

				State = 316; parameterModifier();
				}
				break;
			}
			State = 320;
			_la = _input.La(1);
			if (_la==WS) {
				{
				State = 319; Match(WS);
				}
			}

			State = 322; Match(T__12);
			State = 323; type();
			State = 324; Match(T__13);
			State = 326;
			_la = _input.La(1);
			if (_la==WS) {
				{
				State = 325; Match(WS);
				}
			}

			State = 328; id();
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParameterModifierContext : ParserRuleContext {
		public ParamsModifierContext paramsModifier() {
			return GetRuleContext<ParamsModifierContext>(0);
		}
		public OptsModifierContext optsModifier() {
			return GetRuleContext<OptsModifierContext>(0);
		}
		public RefModifierContext refModifier() {
			return GetRuleContext<RefModifierContext>(0);
		}
		public OutModifierContext outModifier() {
			return GetRuleContext<OutModifierContext>(0);
		}
		public ExtensionModifierContext extensionModifier() {
			return GetRuleContext<ExtensionModifierContext>(0);
		}
		public ParameterModifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_parameterModifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterParameterModifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitParameterModifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParameterModifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParameterModifierContext parameterModifier() {
		ParameterModifierContext _localctx = new ParameterModifierContext(_ctx, State);
		EnterRule(_localctx, 66, RULE_parameterModifier);
		try {
			State = 335;
			switch (_input.La(1)) {
			case T__20:
				EnterOuterAlt(_localctx, 1);
				{
				State = 330; paramsModifier();
				}
				break;
			case T__21:
				EnterOuterAlt(_localctx, 2);
				{
				State = 331; optsModifier();
				}
				break;
			case T__22:
				EnterOuterAlt(_localctx, 3);
				{
				State = 332; refModifier();
				}
				break;
			case T__23:
				EnterOuterAlt(_localctx, 4);
				{
				State = 333; outModifier();
				}
				break;
			case T__24:
				EnterOuterAlt(_localctx, 5);
				{
				State = 334; extensionModifier();
				}
				break;
			default:
				throw new NoViableAltException(this);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class StaticModifierContext : ParserRuleContext {
		public StaticModifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_staticModifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterStaticModifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitStaticModifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitStaticModifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public StaticModifierContext staticModifier() {
		StaticModifierContext _localctx = new StaticModifierContext(_ctx, State);
		EnterRule(_localctx, 68, RULE_staticModifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 337; Match(T__19);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ParamsModifierContext : ParserRuleContext {
		public ParamsModifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_paramsModifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterParamsModifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitParamsModifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitParamsModifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ParamsModifierContext paramsModifier() {
		ParamsModifierContext _localctx = new ParamsModifierContext(_ctx, State);
		EnterRule(_localctx, 70, RULE_paramsModifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 339; Match(T__20);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OptsModifierContext : ParserRuleContext {
		public OptsModifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_optsModifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterOptsModifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitOptsModifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOptsModifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OptsModifierContext optsModifier() {
		OptsModifierContext _localctx = new OptsModifierContext(_ctx, State);
		EnterRule(_localctx, 72, RULE_optsModifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 341; Match(T__21);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class RefModifierContext : ParserRuleContext {
		public RefModifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_refModifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterRefModifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitRefModifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitRefModifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public RefModifierContext refModifier() {
		RefModifierContext _localctx = new RefModifierContext(_ctx, State);
		EnterRule(_localctx, 74, RULE_refModifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 343; Match(T__22);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class OutModifierContext : ParserRuleContext {
		public OutModifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_outModifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterOutModifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitOutModifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitOutModifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public OutModifierContext outModifier() {
		OutModifierContext _localctx = new OutModifierContext(_ctx, State);
		EnterRule(_localctx, 76, RULE_outModifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 345; Match(T__23);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class ExtensionModifierContext : ParserRuleContext {
		public ExtensionModifierContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_extensionModifier; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterExtensionModifier(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitExtensionModifier(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitExtensionModifier(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public ExtensionModifierContext extensionModifier() {
		ExtensionModifierContext _localctx = new ExtensionModifierContext(_ctx, State);
		EnterRule(_localctx, 78, RULE_extensionModifier);
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 347; Match(T__24);
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class IdContext : ParserRuleContext {
		public ITerminalNode[] LETTER() { return GetTokens(TypeNamingParser.LETTER); }
		public ITerminalNode LETTER(int i) {
			return GetToken(TypeNamingParser.LETTER, i);
		}
		public NumContext[] num() {
			return GetRuleContexts<NumContext>();
		}
		public NumContext num(int i) {
			return GetRuleContext<NumContext>(i);
		}
		public ITerminalNode[] SIGN() { return GetTokens(TypeNamingParser.SIGN); }
		public ITerminalNode SIGN(int i) {
			return GetToken(TypeNamingParser.SIGN, i);
		}
		public IdContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_id; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterId(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitId(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitId(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public IdContext id() {
		IdContext _localctx = new IdContext(_ctx, State);
		EnterRule(_localctx, 80, RULE_id);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 349; Match(LETTER);
			State = 355;
			_errHandler.Sync(this);
			_la = _input.La(1);
			while ((((_la) & ~0x3f) == 0 && ((1L << _la) & ((1L << T__25) | (1L << POSNUM) | (1L << LETTER) | (1L << SIGN))) != 0)) {
				{
				State = 353;
				switch (_input.La(1)) {
				case LETTER:
					{
					State = 350; Match(LETTER);
					}
					break;
				case T__25:
				case POSNUM:
					{
					State = 351; num();
					}
					break;
				case SIGN:
					{
					State = 352; Match(SIGN);
					}
					break;
				default:
					throw new NoViableAltException(this);
				}
				}
				State = 357;
				_errHandler.Sync(this);
				_la = _input.La(1);
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public partial class NumContext : ParserRuleContext {
		public ITerminalNode POSNUM() { return GetToken(TypeNamingParser.POSNUM, 0); }
		public NumContext(ParserRuleContext parent, int invokingState)
			: base(parent, invokingState)
		{
		}
		public override int RuleIndex { get { return RULE_num; } }
		public override void EnterRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.EnterNum(this);
		}
		public override void ExitRule(IParseTreeListener listener) {
			ITypeNamingListener typedListener = listener as ITypeNamingListener;
			if (typedListener != null) typedListener.ExitNum(this);
		}
		public override TResult Accept<TResult>(IParseTreeVisitor<TResult> visitor) {
			ITypeNamingVisitor<TResult> typedVisitor = visitor as ITypeNamingVisitor<TResult>;
			if (typedVisitor != null) return typedVisitor.VisitNum(this);
			else return visitor.VisitChildren(this);
		}
	}

	[RuleVersion(0)]
	public NumContext num() {
		NumContext _localctx = new NumContext(_ctx, State);
		EnterRule(_localctx, 82, RULE_num);
		int _la;
		try {
			EnterOuterAlt(_localctx, 1);
			{
			State = 358;
			_la = _input.La(1);
			if ( !(_la==T__25 || _la==POSNUM) ) {
			_errHandler.RecoverInline(this);
			} else {
				Consume();
			}
			}
		}
		catch (RecognitionException re) {
			_localctx.exception = re;
			_errHandler.ReportError(this, re);
			_errHandler.Recover(this, re);
		}
		finally {
			ExitRule();
		}
		return _localctx;
	}

	public static readonly string _serializedATN =
		"\x3\xAF6F\x8320\x479D\xB75C\x4880\x1605\x191C\xAB37\x3\"\x16B\x4\x2\t"+
		"\x2\x4\x3\t\x3\x4\x4\t\x4\x4\x5\t\x5\x4\x6\t\x6\x4\a\t\a\x4\b\t\b\x4\t"+
		"\t\t\x4\n\t\n\x4\v\t\v\x4\f\t\f\x4\r\t\r\x4\xE\t\xE\x4\xF\t\xF\x4\x10"+
		"\t\x10\x4\x11\t\x11\x4\x12\t\x12\x4\x13\t\x13\x4\x14\t\x14\x4\x15\t\x15"+
		"\x4\x16\t\x16\x4\x17\t\x17\x4\x18\t\x18\x4\x19\t\x19\x4\x1A\t\x1A\x4\x1B"+
		"\t\x1B\x4\x1C\t\x1C\x4\x1D\t\x1D\x4\x1E\t\x1E\x4\x1F\t\x1F\x4 \t \x4!"+
		"\t!\x4\"\t\"\x4#\t#\x4$\t$\x4%\t%\x4&\t&\x4\'\t\'\x4(\t(\x4)\t)\x4*\t"+
		"*\x4+\t+\x3\x2\x3\x2\x3\x2\x3\x3\x3\x3\x3\x3\x3\x4\x3\x4\x3\x4\x3\x5\x3"+
		"\x5\x3\x5\x3\x6\x3\x6\x3\x6\x3\a\x3\a\x3\a\x3\a\x3\a\x5\ak\n\a\x3\b\x3"+
		"\b\x5\bo\n\b\x3\b\x3\b\x5\bs\n\b\x3\b\x5\bv\n\b\x3\t\x3\t\x3\t\x3\t\x3"+
		"\t\x5\t}\n\t\x3\n\x3\n\x5\n\x81\n\n\x3\n\x3\n\x5\n\x85\n\n\x3\n\x3\n\x3"+
		"\v\x3\v\x3\v\x3\f\x3\f\x3\f\x3\f\x3\f\x3\r\x3\r\x3\r\x3\r\x3\r\x3\xE\x3"+
		"\xE\x5\xE\x98\n\xE\x3\xF\x5\xF\x9B\n\xF\x3\xF\x3\xF\x3\x10\x3\x10\x3\x10"+
		"\x6\x10\xA2\n\x10\r\x10\xE\x10\xA3\x3\x11\x3\x11\x5\x11\xA8\n\x11\x3\x12"+
		"\x3\x12\x3\x12\x5\x12\xAD\n\x12\x3\x12\x5\x12\xB0\n\x12\x3\x13\x3\x13"+
		"\x3\x13\x3\x14\x3\x14\x3\x14\x3\x15\x3\x15\x3\x15\x3\x16\x3\x16\x3\x17"+
		"\x3\x17\x3\x17\x3\x17\x3\x17\x3\x17\a\x17\xC3\n\x17\f\x17\xE\x17\xC6\v"+
		"\x17\x3\x17\x3\x17\x3\x18\x3\x18\x3\x18\x3\x18\x3\x19\x3\x19\x5\x19\xD0"+
		"\n\x19\x3\x1A\x3\x1A\x3\x1A\a\x1A\xD5\n\x1A\f\x1A\xE\x1A\xD8\v\x1A\x3"+
		"\x1A\x3\x1A\x3\x1A\x5\x1A\xDD\n\x1A\x3\x1A\x5\x1A\xE0\n\x1A\x3\x1B\x3"+
		"\x1B\x3\x1B\x3\x1B\x3\x1B\x3\x1B\x3\x1B\x3\x1B\x3\x1C\x3\x1C\x5\x1C\xEC"+
		"\n\x1C\x3\x1D\x3\x1D\x3\x1D\x5\x1D\xF1\n\x1D\x3\x1D\x3\x1D\x3\x1E\x3\x1E"+
		"\x5\x1E\xF7\n\x1E\x3\x1E\x3\x1E\x5\x1E\xFB\n\x1E\x3\x1E\x3\x1E\x5\x1E"+
		"\xFF\n\x1E\x3\x1E\a\x1E\x102\n\x1E\f\x1E\xE\x1E\x105\v\x1E\x5\x1E\x107"+
		"\n\x1E\x3\x1E\x5\x1E\x10A\n\x1E\x3\x1E\x3\x1E\x3\x1F\x5\x1F\x10F\n\x1F"+
		"\x3\x1F\x3\x1F\x3\x1F\x3\x1F\x5\x1F\x115\n\x1F\x3\x1F\x3\x1F\x3\x1F\x3"+
		"\x1F\x3 \x3 \x5 \x11D\n \x3 \x3 \x3 \x3 \x5 \x123\n \x3 \x3 \x3 \x3 \x3"+
		"!\x5!\x12A\n!\x3!\x5!\x12D\n!\x3!\x3!\x3!\x3!\x5!\x133\n!\x3!\x3!\x3!"+
		"\x3!\x3!\x5!\x13A\n!\x3\"\x5\"\x13D\n\"\x3\"\x5\"\x140\n\"\x3\"\x5\"\x143"+
		"\n\"\x3\"\x3\"\x3\"\x3\"\x5\"\x149\n\"\x3\"\x3\"\x3#\x3#\x3#\x3#\x3#\x5"+
		"#\x152\n#\x3$\x3$\x3%\x3%\x3&\x3&\x3\'\x3\'\x3(\x3(\x3)\x3)\x3*\x3*\x3"+
		"*\x3*\a*\x164\n*\f*\xE*\x167\v*\x3+\x3+\x3+\x2\x2\x2,\x2\x2\x4\x2\x6\x2"+
		"\b\x2\n\x2\f\x2\xE\x2\x10\x2\x12\x2\x14\x2\x16\x2\x18\x2\x1A\x2\x1C\x2"+
		"\x1E\x2 \x2\"\x2$\x2&\x2(\x2*\x2,\x2.\x2\x30\x2\x32\x2\x34\x2\x36\x2\x38"+
		"\x2:\x2<\x2>\x2@\x2\x42\x2\x44\x2\x46\x2H\x2J\x2L\x2N\x2P\x2R\x2T\x2\x2"+
		"\x3\x4\x2\x1C\x1C\x1E\x1E\x175\x2V\x3\x2\x2\x2\x4Y\x3\x2\x2\x2\x6\\\x3"+
		"\x2\x2\x2\b_\x3\x2\x2\x2\n\x62\x3\x2\x2\x2\fj\x3\x2\x2\x2\xEl\x3\x2\x2"+
		"\x2\x10|\x3\x2\x2\x2\x12\x80\x3\x2\x2\x2\x14\x88\x3\x2\x2\x2\x16\x8B\x3"+
		"\x2\x2\x2\x18\x90\x3\x2\x2\x2\x1A\x97\x3\x2\x2\x2\x1C\x9A\x3\x2\x2\x2"+
		"\x1E\xA1\x3\x2\x2\x2 \xA7\x3\x2\x2\x2\"\xAC\x3\x2\x2\x2$\xB1\x3\x2\x2"+
		"\x2&\xB4\x3\x2\x2\x2(\xB7\x3\x2\x2\x2*\xBA\x3\x2\x2\x2,\xBC\x3\x2\x2\x2"+
		".\xC9\x3\x2\x2\x2\x30\xCF\x3\x2\x2\x2\x32\xD6\x3\x2\x2\x2\x34\xE1\x3\x2"+
		"\x2\x2\x36\xEB\x3\x2\x2\x2\x38\xF0\x3\x2\x2\x2:\xF4\x3\x2\x2\x2<\x10E"+
		"\x3\x2\x2\x2>\x11A\x3\x2\x2\x2@\x129\x3\x2\x2\x2\x42\x13F\x3\x2\x2\x2"+
		"\x44\x151\x3\x2\x2\x2\x46\x153\x3\x2\x2\x2H\x155\x3\x2\x2\x2J\x157\x3"+
		"\x2\x2\x2L\x159\x3\x2\x2\x2N\x15B\x3\x2\x2\x2P\x15D\x3\x2\x2\x2R\x15F"+
		"\x3\x2\x2\x2T\x168\x3\x2\x2\x2VW\x5\f\a\x2WX\a\"\x2\x2X\x3\x3\x2\x2\x2"+
		"YZ\x5\x36\x1C\x2Z[\a\"\x2\x2[\x5\x3\x2\x2\x2\\]\x5\x1E\x10\x2]^\a\"\x2"+
		"\x2^\a\x3\x2\x2\x2_`\x5\x30\x19\x2`\x61\a\"\x2\x2\x61\t\x3\x2\x2\x2\x62"+
		"\x63\x5\x42\"\x2\x63\x64\a\"\x2\x2\x64\v\x3\x2\x2\x2\x65k\a\x1D\x2\x2"+
		"\x66k\x5\xE\b\x2gk\x5\x12\n\x2hk\x5\x14\v\x2ik\x5\x16\f\x2j\x65\x3\x2"+
		"\x2\x2j\x66\x3\x2\x2\x2jg\x3\x2\x2\x2jh\x3\x2\x2\x2ji\x3\x2\x2\x2k\r\x3"+
		"\x2\x2\x2lu\x5R*\x2mo\a!\x2\x2nm\x3\x2\x2\x2no\x3\x2\x2\x2op\x3\x2\x2"+
		"\x2pr\a\x3\x2\x2qs\a!\x2\x2rq\x3\x2\x2\x2rs\x3\x2\x2\x2st\x3\x2\x2\x2"+
		"tv\x5\x10\t\x2un\x3\x2\x2\x2uv\x3\x2\x2\x2v\xF\x3\x2\x2\x2w}\x5\x12\n"+
		"\x2x}\x5\x14\v\x2y}\x5\x16\f\x2z}\a\x1D\x2\x2{}\x5R*\x2|w\x3\x2\x2\x2"+
		"|x\x3\x2\x2\x2|y\x3\x2\x2\x2|z\x3\x2\x2\x2|{\x3\x2\x2\x2}\x11\x3\x2\x2"+
		"\x2~\x81\x5\x1C\xF\x2\x7F\x81\x5\x18\r\x2\x80~\x3\x2\x2\x2\x80\x7F\x3"+
		"\x2\x2\x2\x81\x82\x3\x2\x2\x2\x82\x84\a\x4\x2\x2\x83\x85\a!\x2\x2\x84"+
		"\x83\x3\x2\x2\x2\x84\x85\x3\x2\x2\x2\x85\x86\x3\x2\x2\x2\x86\x87\x5\x30"+
		"\x19\x2\x87\x13\x3\x2\x2\x2\x88\x89\a\x5\x2\x2\x89\x8A\x5\x36\x1C\x2\x8A"+
		"\x15\x3\x2\x2\x2\x8B\x8C\a\x6\x2\x2\x8C\x8D\a\x1E\x2\x2\x8D\x8E\a\a\x2"+
		"\x2\x8E\x8F\x5\f\a\x2\x8F\x17\x3\x2\x2\x2\x90\x91\a\b\x2\x2\x91\x92\x5"+
		"\x1A\xE\x2\x92\x93\a\t\x2\x2\x93\x94\x5 \x11\x2\x94\x19\x3\x2\x2\x2\x95"+
		"\x98\x5\x18\r\x2\x96\x98\x5\x1C\xF\x2\x97\x95\x3\x2\x2\x2\x97\x96\x3\x2"+
		"\x2\x2\x98\x1B\x3\x2\x2\x2\x99\x9B\x5\x1E\x10\x2\x9A\x99\x3\x2\x2\x2\x9A"+
		"\x9B\x3\x2\x2\x2\x9B\x9C\x3\x2\x2\x2\x9C\x9D\x5 \x11\x2\x9D\x1D\x3\x2"+
		"\x2\x2\x9E\x9F\x5R*\x2\x9F\xA0\a\n\x2\x2\xA0\xA2\x3\x2\x2\x2\xA1\x9E\x3"+
		"\x2\x2\x2\xA2\xA3\x3\x2\x2\x2\xA3\xA1\x3\x2\x2\x2\xA3\xA4\x3\x2\x2\x2"+
		"\xA4\x1F\x3\x2\x2\x2\xA5\xA8\x5$\x13\x2\xA6\xA8\x5\"\x12\x2\xA7\xA5\x3"+
		"\x2\x2\x2\xA7\xA6\x3\x2\x2\x2\xA8!\x3\x2\x2\x2\xA9\xAD\x5&\x14\x2\xAA"+
		"\xAD\x5(\x15\x2\xAB\xAD\x5*\x16\x2\xAC\xA9\x3\x2\x2\x2\xAC\xAA\x3\x2\x2"+
		"\x2\xAC\xAB\x3\x2\x2\x2\xAD\xAF\x3\x2\x2\x2\xAE\xB0\x5,\x17\x2\xAF\xAE"+
		"\x3\x2\x2\x2\xAF\xB0\x3\x2\x2\x2\xB0#\x3\x2\x2\x2\xB1\xB2\a\v\x2\x2\xB2"+
		"\xB3\x5*\x16\x2\xB3%\x3\x2\x2\x2\xB4\xB5\a\f\x2\x2\xB5\xB6\x5*\x16\x2"+
		"\xB6\'\x3\x2\x2\x2\xB7\xB8\a\r\x2\x2\xB8\xB9\x5*\x16\x2\xB9)\x3\x2\x2"+
		"\x2\xBA\xBB\x5R*\x2\xBB+\x3\x2\x2\x2\xBC\xBD\a\xE\x2\x2\xBD\xBE\a\x1E"+
		"\x2\x2\xBE\xBF\a\xF\x2\x2\xBF\xC4\x5.\x18\x2\xC0\xC1\a\x4\x2\x2\xC1\xC3"+
		"\x5.\x18\x2\xC2\xC0\x3\x2\x2\x2\xC3\xC6\x3\x2\x2\x2\xC4\xC2\x3\x2\x2\x2"+
		"\xC4\xC5\x3\x2\x2\x2\xC5\xC7\x3\x2\x2\x2\xC6\xC4\x3\x2\x2\x2\xC7\xC8\a"+
		"\x10\x2\x2\xC8-\x3\x2\x2\x2\xC9\xCA\a\xF\x2\x2\xCA\xCB\x5\xE\b\x2\xCB"+
		"\xCC\a\x10\x2\x2\xCC/\x3\x2\x2\x2\xCD\xD0\x5\x32\x1A\x2\xCE\xD0\a\x1D"+
		"\x2\x2\xCF\xCD\x3\x2\x2\x2\xCF\xCE\x3\x2\x2\x2\xD0\x31\x3\x2\x2\x2\xD1"+
		"\xD2\x5R*\x2\xD2\xD3\a\n\x2\x2\xD3\xD5\x3\x2\x2\x2\xD4\xD1\x3\x2\x2\x2"+
		"\xD5\xD8\x3\x2\x2\x2\xD6\xD4\x3\x2\x2\x2\xD6\xD7\x3\x2\x2\x2\xD7\xD9\x3"+
		"\x2\x2\x2\xD8\xD6\x3\x2\x2\x2\xD9\xDF\x5R*\x2\xDA\xDC\a\x4\x2\x2\xDB\xDD"+
		"\a!\x2\x2\xDC\xDB\x3\x2\x2\x2\xDC\xDD\x3\x2\x2\x2\xDD\xDE\x3\x2\x2\x2"+
		"\xDE\xE0\x5\x34\x1B\x2\xDF\xDA\x3\x2\x2\x2\xDF\xE0\x3\x2\x2\x2\xE0\x33"+
		"\x3\x2\x2\x2\xE1\xE2\x5T+\x2\xE2\xE3\a\n\x2\x2\xE3\xE4\x5T+\x2\xE4\xE5"+
		"\a\n\x2\x2\xE5\xE6\x5T+\x2\xE6\xE7\a\n\x2\x2\xE7\xE8\x5T+\x2\xE8\x35\x3"+
		"\x2\x2\x2\xE9\xEC\a\x1D\x2\x2\xEA\xEC\x5\x38\x1D\x2\xEB\xE9\x3\x2\x2\x2"+
		"\xEB\xEA\x3\x2\x2\x2\xEC\x37\x3\x2\x2\x2\xED\xF1\x5<\x1F\x2\xEE\xF1\x5"+
		"> \x2\xEF\xF1\x5@!\x2\xF0\xED\x3\x2\x2\x2\xF0\xEE\x3\x2\x2\x2\xF0\xEF"+
		"\x3\x2\x2\x2\xF1\xF2\x3\x2\x2\x2\xF2\xF3\x5:\x1E\x2\xF3\x39\x3\x2\x2\x2"+
		"\xF4\xF6\a\x11\x2\x2\xF5\xF7\a!\x2\x2\xF6\xF5\x3\x2\x2\x2\xF6\xF7\x3\x2"+
		"\x2\x2\xF7\x106\x3\x2\x2\x2\xF8\x103\x5\x42\"\x2\xF9\xFB\a!\x2\x2\xFA"+
		"\xF9\x3\x2\x2\x2\xFA\xFB\x3\x2\x2\x2\xFB\xFC\x3\x2\x2\x2\xFC\xFE\a\x4"+
		"\x2\x2\xFD\xFF\a!\x2\x2\xFE\xFD\x3\x2\x2\x2\xFE\xFF\x3\x2\x2\x2\xFF\x100"+
		"\x3\x2\x2\x2\x100\x102\x5\x42\"\x2\x101\xFA\x3\x2\x2\x2\x102\x105\x3\x2"+
		"\x2\x2\x103\x101\x3\x2\x2\x2\x103\x104\x3\x2\x2\x2\x104\x107\x3\x2\x2"+
		"\x2\x105\x103\x3\x2\x2\x2\x106\xF8\x3\x2\x2\x2\x106\x107\x3\x2\x2\x2\x107"+
		"\x109\x3\x2\x2\x2\x108\x10A\a!\x2\x2\x109\x108\x3\x2\x2\x2\x109\x10A\x3"+
		"\x2\x2\x2\x10A\x10B\x3\x2\x2\x2\x10B\x10C\a\x12\x2\x2\x10C;\x3\x2\x2\x2"+
		"\x10D\x10F\a!\x2\x2\x10E\x10D\x3\x2\x2\x2\x10E\x10F\x3\x2\x2\x2\x10F\x110"+
		"\x3\x2\x2\x2\x110\x111\a\xF\x2\x2\x111\x112\a\x1D\x2\x2\x112\x114\a\x10"+
		"\x2\x2\x113\x115\a!\x2\x2\x114\x113\x3\x2\x2\x2\x114\x115\x3\x2\x2\x2"+
		"\x115\x116\x3\x2\x2\x2\x116\x117\a\xF\x2\x2\x117\x118\x5\f\a\x2\x118\x119"+
		"\a\x13\x2\x2\x119=\x3\x2\x2\x2\x11A\x11C\x5\x46$\x2\x11B\x11D\a!\x2\x2"+
		"\x11C\x11B\x3\x2\x2\x2\x11C\x11D\x3\x2\x2\x2\x11D\x11E\x3\x2\x2\x2\x11E"+
		"\x11F\a\xF\x2\x2\x11F\x120\a\x1D\x2\x2\x120\x122\a\x10\x2\x2\x121\x123"+
		"\a!\x2\x2\x122\x121\x3\x2\x2\x2\x122\x123\x3\x2\x2\x2\x123\x124\x3\x2"+
		"\x2\x2\x124\x125\a\xF\x2\x2\x125\x126\x5\f\a\x2\x126\x127\a\x14\x2\x2"+
		"\x127?\x3\x2\x2\x2\x128\x12A\x5\x46$\x2\x129\x128\x3\x2\x2\x2\x129\x12A"+
		"\x3\x2\x2\x2\x12A\x12C\x3\x2\x2\x2\x12B\x12D\a!\x2\x2\x12C\x12B\x3\x2"+
		"\x2\x2\x12C\x12D\x3\x2\x2\x2\x12D\x12E\x3\x2\x2\x2\x12E\x12F\a\xF\x2\x2"+
		"\x12F\x130\x5\f\a\x2\x130\x132\a\x10\x2\x2\x131\x133\a!\x2\x2\x132\x131"+
		"\x3\x2\x2\x2\x132\x133\x3\x2\x2\x2\x133\x134\x3\x2\x2\x2\x134\x135\a\xF"+
		"\x2\x2\x135\x136\x5\f\a\x2\x136\x137\a\x15\x2\x2\x137\x139\x5R*\x2\x138"+
		"\x13A\x5,\x17\x2\x139\x138\x3\x2\x2\x2\x139\x13A\x3\x2\x2\x2\x13A\x41"+
		"\x3\x2\x2\x2\x13B\x13D\a!\x2\x2\x13C\x13B\x3\x2\x2\x2\x13C\x13D\x3\x2"+
		"\x2\x2\x13D\x13E\x3\x2\x2\x2\x13E\x140\x5\x44#\x2\x13F\x13C\x3\x2\x2\x2"+
		"\x13F\x140\x3\x2\x2\x2\x140\x142\x3\x2\x2\x2\x141\x143\a!\x2\x2\x142\x141"+
		"\x3\x2\x2\x2\x142\x143\x3\x2\x2\x2\x143\x144\x3\x2\x2\x2\x144\x145\a\xF"+
		"\x2\x2\x145\x146\x5\f\a\x2\x146\x148\a\x10\x2\x2\x147\x149\a!\x2\x2\x148"+
		"\x147\x3\x2\x2\x2\x148\x149\x3\x2\x2\x2\x149\x14A\x3\x2\x2\x2\x14A\x14B"+
		"\x5R*\x2\x14B\x43\x3\x2\x2\x2\x14C\x152\x5H%\x2\x14D\x152\x5J&\x2\x14E"+
		"\x152\x5L\'\x2\x14F\x152\x5N(\x2\x150\x152\x5P)\x2\x151\x14C\x3\x2\x2"+
		"\x2\x151\x14D\x3\x2\x2\x2\x151\x14E\x3\x2\x2\x2\x151\x14F\x3\x2\x2\x2"+
		"\x151\x150\x3\x2\x2\x2\x152\x45\x3\x2\x2\x2\x153\x154\a\x16\x2\x2\x154"+
		"G\x3\x2\x2\x2\x155\x156\a\x17\x2\x2\x156I\x3\x2\x2\x2\x157\x158\a\x18"+
		"\x2\x2\x158K\x3\x2\x2\x2\x159\x15A\a\x19\x2\x2\x15AM\x3\x2\x2\x2\x15B"+
		"\x15C\a\x1A\x2\x2\x15CO\x3\x2\x2\x2\x15D\x15E\a\x1B\x2\x2\x15EQ\x3\x2"+
		"\x2\x2\x15F\x165\a\x1F\x2\x2\x160\x164\a\x1F\x2\x2\x161\x164\x5T+\x2\x162"+
		"\x164\a \x2\x2\x163\x160\x3\x2\x2\x2\x163\x161\x3\x2\x2\x2\x163\x162\x3"+
		"\x2\x2\x2\x164\x167\x3\x2\x2\x2\x165\x163\x3\x2\x2\x2\x165\x166\x3\x2"+
		"\x2\x2\x166S\x3\x2\x2\x2\x167\x165\x3\x2\x2\x2\x168\x169\t\x2\x2\x2\x169"+
		"U\x3\x2\x2\x2+jnru|\x80\x84\x97\x9A\xA3\xA7\xAC\xAF\xC4\xCF\xD6\xDC\xDF"+
		"\xEB\xF0\xF6\xFA\xFE\x103\x106\x109\x10E\x114\x11C\x122\x129\x12C\x132"+
		"\x139\x13C\x13F\x142\x148\x151\x163\x165";
	public static readonly ATN _ATN =
		new ATNDeserializer().Deserialize(_serializedATN.ToCharArray());
}
} // namespace KaVE.Commons.Model.Names.CSharp.Parser
