//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVE.FeedbackProcessor.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaVE.FeedbackProcessor.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command ID,Mapping
        ///_Unshelve,PM
        ///{00000000-0000-0000-0000-313370000001}:56:VSCommands.BreakInCurrentDocument,D
        ///{132320BA-BC11-4A1E-8E7A-6833DD4D4D39}:256:Tools.WCFServiceConfigurationEditor,
        ///{1496A755-94DE-11D0-8C3F-00C04FC2AAE2}:103:Edit.SelectionCancel,D
        ///{1496A755-94DE-11D0-8C3F-00C04FC2AAE2}:104:Edit.ParameterInfo,U
        ///{1496A755-94DE-11D0-8C3F-00C04FC2AAE2}:105:Edit.ViewWhiteSpace,LC
        ///{1496A755-94DE-11D0-8C3F-00C04FC2AAE2}:1109:Project.IncludeInProject,D
        ///{1496A755-94DE-11D0-8C3F-00C04FC2AAE2}:1110:Pro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommandIdToActivityMapping {
            get {
                return ResourceManager.GetString("CommandIdToActivityMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FirstCommand,SecondCommand,Count
        ///View History...,{57735D06-C920-4415-A2E0-7D6E6FBDFA99}:4101:Team.Git.ViewHistory,25
        ///View History,{5BF14E63-E267-4787-B20B-B814FD043B38}:21508:File.TfsHistory,3
        ///View Code,{5EFC7975-14BC-11CF-9B2B-00AA00573819}:333:View.ViewCode,4
        ///Unpublish Branch,{57735D06-C920-4415-A2E0-7D6E6FBDFA99}:4116:Team.Git.SwitchBranchPublishState,6
        ///Unload Project,{5EFC7975-14BC-11CF-9B2B-00AA00573819}:413:Project.UnloadProject,1
        ///Undo...,{FFE1131C-8EA1-4D05-9728-34AD4611BDA9}:6356:TeamFoundatio [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommandMappingsStatistic {
            get {
                return ResourceManager.GetString("CommandMappingsStatistic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Command Id;Tool        ///{5EFC7975-14BC-11CF-9B2B-00AA00573819}:26:Edit.Paste;IDE Core        ///KaVE$Completion_Applied;Completion        ///{5EFC7975-14BC-11CF-9B2B-00AA00573819}:15:Edit.Copy;IDE Core        ///KaVE$Completion_Cancelled;Completion        ///{5EFC7975-14BC-11CF-9B2B-00AA00573819}:331:File.SaveSelectedItems;IDE Core        ///{5EFC7975-14BC-11CF-9B2B-00AA00573819}:295:Debug.Start;Debugger        ///{5EFC7975-14BC-11CF-9B2B-00AA00573819}:249:Debug.StepOver;Debugger        ///{5EFC7975-14BC-11CF-9B2B-00AA00573819}:882:Build.BuildSolution;Build        ///{5EFC7975-14BC-11CF-9B2B-0 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CommandToolMapping {
            get {
                return ResourceManager.GetString("CommandToolMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 558840066b05280a2805f90f_01.07.2015
        ///5588414f6b05280a2807770d_11.06.2015
        ///55642e3c6b052826389e3d2b_25.03.2015
        ///556429786b0528263895ac6d_13.02.2015
        ///558841556b05280a28077f33_12.06.2015
        ///55883b916b05280a2800d214_07.05.2015
        ///55883a476b05280a28ff54ea_11.05.2015
        ///55642b976b0528263899685f_31.03.2015
        ///5564291c6b05282638956091_20.03.2015
        ///55642e3c6b052826389e3d2b_30.03.2015
        ///55642e3c6b052826389e3d2b_30.04.2015
        ///55642f5d6b05282638a0bae9_06.05.2015
        ///558844e76b05280a280be420_09.06.2015
        ///55642c156b0528263899f908_30.03. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ExcludedDays {
            get {
                return ResourceManager.GetString("ExcludedDays", resourceCulture);
            }
        }
    }
}
