//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVE.VS.FeedbackGenerator.UserControls.OptionPage.UsageModelOptions {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UsageModelOptionsMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UsageModelOptionsMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaVE.VS.FeedbackGenerator.UserControls.OptionPage.UsageModelOptions.UsageModelOpt" +
                            "ionsMessages", typeof(UsageModelOptionsMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Install.
        /// </summary>
        public static string InstallSelectedModelButton {
            get {
                return ResourceManager.GetString("InstallSelectedModelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs the selected model.
        /// </summary>
        public static string InstallSelectedModelToolTip {
            get {
                return ResourceManager.GetString("InstallSelectedModelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Models.
        /// </summary>
        public static string ReloadModelsButton {
            get {
                return ResourceManager.GetString("ReloadModelsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove all Models.
        /// </summary>
        public static string RemoveAllModelsButton {
            get {
                return ResourceManager.GetString("RemoveAllModelsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remove.
        /// </summary>
        public static string RemoveSelectedModelButton {
            get {
                return ResourceManager.GetString("RemoveSelectedModelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Removes the selected model.
        /// </summary>
        public static string RemoveSelectedModelToolTip {
            get {
                return ResourceManager.GetString("RemoveSelectedModelToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Usage Model Settings.
        /// </summary>
        public static string SettingResetButton {
            get {
                return ResourceManager.GetString("SettingResetButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Model Settings will be reset. Are you sure?.
        /// </summary>
        public static string SettingResetDialog {
            get {
                return ResourceManager.GetString("SettingResetDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update all Models.
        /// </summary>
        public static string UpdateAllModelsButton {
            get {
                return ResourceManager.GetString("UpdateAllModelsButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string UpdateSelectedModelButton {
            get {
                return ResourceManager.GetString("UpdateSelectedModelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Installs the newest version of the selected model.
        /// </summary>
        public static string UpdateSelectedModelToolTip {
            get {
                return ResourceManager.GetString("UpdateSelectedModelToolTip", resourceCulture);
            }
        }
    }
}
