//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVE.VS.Achievements.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class categories {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal categories() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaVE.VS.Achievements.Properties.categories", typeof(categories).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding.
        /// </summary>
        internal static string Category_1 {
            get {
                return ResourceManager.GetString("Category_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_10 {
            get {
                return ResourceManager.GetString("Category_10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_11 {
            get {
                return ResourceManager.GetString("Category_11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_12 {
            get {
                return ResourceManager.GetString("Category_12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_13 {
            get {
                return ResourceManager.GetString("Category_13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_14 {
            get {
                return ResourceManager.GetString("Category_14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FeatOfStrength.
        /// </summary>
        internal static string Category_15 {
            get {
                return ResourceManager.GetString("Category_15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resharper.
        /// </summary>
        internal static string Category_16 {
            get {
                return ResourceManager.GetString("Category_16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resharper.
        /// </summary>
        internal static string Category_17 {
            get {
                return ResourceManager.GetString("Category_17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resharper.
        /// </summary>
        internal static string Category_18 {
            get {
                return ResourceManager.GetString("Category_18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resharper.
        /// </summary>
        internal static string Category_19 {
            get {
                return ResourceManager.GetString("Category_19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding.
        /// </summary>
        internal static string Category_2 {
            get {
                return ResourceManager.GetString("Category_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resharper.
        /// </summary>
        internal static string Category_20 {
            get {
                return ResourceManager.GetString("Category_20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resharper.
        /// </summary>
        internal static string Category_21 {
            get {
                return ResourceManager.GetString("Category_21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_22 {
            get {
                return ResourceManager.GetString("Category_22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_23 {
            get {
                return ResourceManager.GetString("Category_23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_24 {
            get {
                return ResourceManager.GetString("Category_24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding.
        /// </summary>
        internal static string Category_25 {
            get {
                return ResourceManager.GetString("Category_25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding.
        /// </summary>
        internal static string Category_26 {
            get {
                return ResourceManager.GetString("Category_26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding.
        /// </summary>
        internal static string Category_27 {
            get {
                return ResourceManager.GetString("Category_27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding.
        /// </summary>
        internal static string Category_28 {
            get {
                return ResourceManager.GetString("Category_28", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding.
        /// </summary>
        internal static string Category_29 {
            get {
                return ResourceManager.GetString("Category_29", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding.
        /// </summary>
        internal static string Category_3 {
            get {
                return ResourceManager.GetString("Category_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_30 {
            get {
                return ResourceManager.GetString("Category_30", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_31 {
            get {
                return ResourceManager.GetString("Category_31", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_32 {
            get {
                return ResourceManager.GetString("Category_32", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_33 {
            get {
                return ResourceManager.GetString("Category_33", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_34 {
            get {
                return ResourceManager.GetString("Category_34", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_35 {
            get {
                return ResourceManager.GetString("Category_35", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_36 {
            get {
                return ResourceManager.GetString("Category_36", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_37 {
            get {
                return ResourceManager.GetString("Category_37", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_38 {
            get {
                return ResourceManager.GetString("Category_38", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_39 {
            get {
                return ResourceManager.GetString("Category_39", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding.
        /// </summary>
        internal static string Category_4 {
            get {
                return ResourceManager.GetString("Category_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding.
        /// </summary>
        internal static string Category_5 {
            get {
                return ResourceManager.GetString("Category_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string Category_6 {
            get {
                return ResourceManager.GetString("Category_6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_7 {
            get {
                return ResourceManager.GetString("Category_7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_8 {
            get {
                return ResourceManager.GetString("Category_8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Category_9 {
            get {
                return ResourceManager.GetString("Category_9", resourceCulture);
            }
        }
    }
}
