//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVE.VS.Achievements.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class StatisticPropertyNames {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal StatisticPropertyNames() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaVE.VS.Achievements.Properties.StatisticPropertyNames", typeof(StatisticPropertyNames).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average saved key inputs.
        /// </summary>
        public static string AverageSavedKeystrokes {
            get {
                return ResourceManager.GetString("AverageSavedKeystrokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average time in failed code completions.
        /// </summary>
        public static string AverageTimeCancelled {
            get {
                return ResourceManager.GetString("AverageTimeCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average time in applied code completions.
        /// </summary>
        public static string AverageTimeCompleted {
            get {
                return ResourceManager.GetString("AverageTimeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current number of code edits since last commit.
        /// </summary>
        public static string CurrentNumberOfEditsBetweenCommits {
            get {
                return ResourceManager.GetString("CurrentNumberOfEditsBetweenCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Earliest event time.
        /// </summary>
        public static string EarliestEventTime {
            get {
                return ResourceManager.GetString("EarliestEventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of failed builds.
        /// </summary>
        public static string FailedBuilds {
            get {
                return ResourceManager.GetString("FailedBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest event time.
        /// </summary>
        public static string LatestEventTime {
            get {
                return ResourceManager.GetString("LatestEventTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum number of code edits between two commits.
        /// </summary>
        public static string MaxNumberOfEditsBetweenCommits {
            get {
                return ResourceManager.GetString("MaxNumberOfEditsBetweenCommits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of items added to projects.
        /// </summary>
        public static string ProjectItemsAdded {
            get {
                return ResourceManager.GetString("ProjectItemsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of items removed in projects.
        /// </summary>
        public static string ProjectItemsRemoved {
            get {
                return ResourceManager.GetString("ProjectItemsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of items renamed in projects.
        /// </summary>
        public static string ProjectItemsRenamed {
            get {
                return ResourceManager.GetString("ProjectItemsRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of added projects.
        /// </summary>
        public static string ProjectsAdded {
            get {
                return ResourceManager.GetString("ProjectsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of removed projects.
        /// </summary>
        public static string ProjectsRemoved {
            get {
                return ResourceManager.GetString("ProjectsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of renamed projects.
        /// </summary>
        public static string ProjectsRenamed {
            get {
                return ResourceManager.GetString("ProjectsRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved key inputs.
        /// </summary>
        public static string SavedKeystrokes {
            get {
                return ResourceManager.GetString("SavedKeystrokes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of items added to solutions.
        /// </summary>
        public static string SolutionItemsAdded {
            get {
                return ResourceManager.GetString("SolutionItemsAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of removed items in solutions.
        /// </summary>
        public static string SolutionItemsRemoved {
            get {
                return ResourceManager.GetString("SolutionItemsRemoved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of items renamed in solutions.
        /// </summary>
        public static string SolutionItemsRenamed {
            get {
                return ResourceManager.GetString("SolutionItemsRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of closed solutions.
        /// </summary>
        public static string SolutionsClosed {
            get {
                return ResourceManager.GetString("SolutionsClosed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of opened solutions.
        /// </summary>
        public static string SolutionsOpened {
            get {
                return ResourceManager.GetString("SolutionsOpened", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of renamed solutions.
        /// </summary>
        public static string SolutionsRenamed {
            get {
                return ResourceManager.GetString("SolutionsRenamed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of successful builds.
        /// </summary>
        public static string SuccessfulBuilds {
            get {
                return ResourceManager.GetString("SuccessfulBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of created test classes.
        /// </summary>
        public static string TestClassesCreated {
            get {
                return ResourceManager.GetString("TestClassesCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximal time in a debug session.
        /// </summary>
        public static string TimeInDebugSession {
            get {
                return ResourceManager.GetString("TimeInDebugSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of builds.
        /// </summary>
        public static string TotalBuilds {
            get {
                return ResourceManager.GetString("TotalBuilds", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of failed code completions.
        /// </summary>
        public static string TotalCancelled {
            get {
                return ResourceManager.GetString("TotalCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of applied code completions.
        /// </summary>
        public static string TotalCompleted {
            get {
                return ResourceManager.GetString("TotalCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of code completions.
        /// </summary>
        public static string TotalCompletions {
            get {
                return ResourceManager.GetString("TotalCompletions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of events.
        /// </summary>
        public static string TotalEvents {
            get {
                return ResourceManager.GetString("TotalEvents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total number of code edits.
        /// </summary>
        public static string TotalNumberOfEdits {
            get {
                return ResourceManager.GetString("TotalNumberOfEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total proposals of code completions.
        /// </summary>
        public static string TotalProposals {
            get {
                return ResourceManager.GetString("TotalProposals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total time in code completions.
        /// </summary>
        public static string TotalTime {
            get {
                return ResourceManager.GetString("TotalTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in failed code completions.
        /// </summary>
        public static string TotalTimeCancelled {
            get {
                return ResourceManager.GetString("TotalTimeCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time in applied code completions.
        /// </summary>
        public static string TotalTimeCompleted {
            get {
                return ResourceManager.GetString("TotalTimeCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total working time.
        /// </summary>
        public static string TotalWorkTime {
            get {
                return ResourceManager.GetString("TotalWorkTime", resourceCulture);
            }
        }
    }
}
