//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVE.VS.Achievements.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UIText {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UIText() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaVE.VS.Achievements.Properties.UIText", typeof(UIText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not Completed.
        /// </summary>
        public static string Achievement_NotCompleted {
            get {
                return ResourceManager.GetString("Achievement_NotCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string AchievementWindow_FilterBox_All {
            get {
                return ResourceManager.GetString("AchievementWindow_FilterBox_All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed.
        /// </summary>
        public static string AchievementWindow_FilterBox_Completed {
            get {
                return ResourceManager.GetString("AchievementWindow_FilterBox_Completed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uncompleted.
        /// </summary>
        public static string AchievementWindow_FilterBox_Uncompleted {
            get {
                return ResourceManager.GetString("AchievementWindow_FilterBox_Uncompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show:.
        /// </summary>
        public static string AchievementWindow_Show {
            get {
                return ResourceManager.GetString("AchievementWindow_Show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CompletionDate.
        /// </summary>
        public static string AchievementWindow_SortBox_CompletionDate {
            get {
                return ResourceManager.GetString("AchievementWindow_SortBox_CompletionDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progression.
        /// </summary>
        public static string AchievementWindow_SortBox_Progression {
            get {
                return ResourceManager.GetString("AchievementWindow_SortBox_Progression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string AchievementWindow_SortBox_Title {
            get {
                return ResourceManager.GetString("AchievementWindow_SortBox_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort By:.
        /// </summary>
        public static string AchievementWindow_SortBy {
            get {
                return ResourceManager.GetString("AchievementWindow_SortBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string Category_1 {
            get {
                return ResourceManager.GetString("Category_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string Category_2 {
            get {
                return ResourceManager.GetString("Category_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string Category_3 {
            get {
                return ResourceManager.GetString("Category_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coding.
        /// </summary>
        public static string Category_4 {
            get {
                return ResourceManager.GetString("Category_4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resharper.
        /// </summary>
        public static string Category_5 {
            get {
                return ResourceManager.GetString("Category_5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feats of Strength.
        /// </summary>
        public static string Category_6 {
            get {
                return ResourceManager.GetString("Category_6", resourceCulture);
            }
        }
    }
}
