//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVE.VsFeedbackGenerator.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UploadWizard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UploadWizard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaVE.VsFeedbackGenerator.Properties.UploadWizard", typeof(UploadWizard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Der Export wird im Hintergrund fortgührt..
        /// </summary>
        public static string ContinueInBackground {
            get {
                return ResourceManager.GetString("ContinueInBackground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erläuterung Upload:....
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exportiere....
        /// </summary>
        public static string Export_BusyMessage {
            get {
                return ResourceManager.GetString("Export_BusyMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direktupload.
        /// </summary>
        public static string export_upload_button {
            get {
                return ResourceManager.GetString("export_upload_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ZIP-Export....
        /// </summary>
        public static string export_zip_button {
            get {
                return ResourceManager.GetString("export_zip_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Beim Exportieren/Versenden des Feedbacks ist ein Fehler aufgetreten!.
        /// </summary>
        public static string ExportFail {
            get {
                return ResourceManager.GetString("ExportFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Das Exportieren/Versenden von {0} Events war erfolgreich..
        /// </summary>
        public static string ExportSuccess {
            get {
                return ResourceManager.GetString("ExportSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zum Hochladen des Feedbacks besuchen Sie bitte die folgende Seite:.
        /// </summary>
        public static string ExportSuccessLinkDescription {
            get {
                return ResourceManager.GetString("ExportSuccessLinkDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Es gibt nichts zu exportieren..
        /// </summary>
        public static string NothingToExport {
            get {
                return ResourceManager.GetString("NothingToExport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback einsehen.
        /// </summary>
        public static string review_link {
            get {
                return ResourceManager.GetString("review_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export-Wizard.
        /// </summary>
        public static string window_title {
            get {
                return ResourceManager.GetString("window_title", resourceCulture);
            }
        }
    }
}
