//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34014
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVE.VsFeedbackGenerator.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class UploadWizard {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UploadWizard() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaVE.VsFeedbackGenerator.Properties.UploadWizard", typeof(UploadWizard).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Anonymisierung.
        /// </summary>
        public static string checkbox_group_name {
            get {
                return ResourceManager.GetString("checkbox_group_name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erläuterung Upload:....
        /// </summary>
        public static string description {
            get {
                return ResourceManager.GetString("description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dauer von Events im Feedback erfassen.
        /// </summary>
        public static string duration_checkbox {
            get {
                return ResourceManager.GetString("duration_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Direktupload.
        /// </summary>
        public static string export_upload_button {
            get {
                return ResourceManager.GetString("export_upload_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zip Export....
        /// </summary>
        public static string export_zip_button {
            get {
                return ResourceManager.GetString("export_zip_button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Methoden- und Variablennamen im Feedback erfassen.
        /// </summary>
        public static string name_checkbox {
            get {
                return ResourceManager.GetString("name_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback einsehen.
        /// </summary>
        public static string review_link {
            get {
                return ResourceManager.GetString("review_link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zuordnung von Events zu Sessions im Feedback erfassen.
        /// </summary>
        public static string sessionId_checkbox {
            get {
                return ResourceManager.GetString("sessionId_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Auslösezeitpunkt von Events im Feedback erfassen.
        /// </summary>
        public static string startTime_checkbox {
            get {
                return ResourceManager.GetString("startTime_checkbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export Wizard.
        /// </summary>
        public static string window_title {
            get {
                return ResourceManager.GetString("window_title", resourceCulture);
            }
        }
    }
}
