//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KaVE.VS.FeedbackGenerator.UserControls.UserProfile {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class UserProfileMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal UserProfileMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("KaVE.VS.FeedbackGenerator.UserControls.UserProfile.UserProfileMessages", typeof(UserProfileMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We would like to learn more about our users, please help us by answering several simple questions about yourself.You can leave out any question, if you do not want to answer it. Your answers will be attached to your uploaded feedback..
        /// </summary>
        internal static string Intro {
            get {
                return ResourceManager.GetString("Intro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On which kind of projects did you regularly work over the last year?.
        /// </summary>
        internal static string Projects_Question {
            get {
                return ResourceManager.GetString("Projects_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assignments from classes or online courses.
        /// </summary>
        internal static string ProjectsCourses {
            get {
                return ResourceManager.GetString("ProjectsCourses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal projects used for learning and exploration that might be publicly available, but exist mainly for personal use.
        /// </summary>
        internal static string ProjectsPersonal {
            get {
                return ResourceManager.GetString("ProjectsPersonal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large open-source or commercial projects with &gt;=50,000 lines of code that are used by others.
        /// </summary>
        internal static string ProjectsSharedLarge {
            get {
                return ResourceManager.GetString("ProjectsSharedLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium open-source or commercial projects with &gt;2,000 and &lt;50,000 lines of code that are used by others.
        /// </summary>
        internal static string ProjectsSharedMedium {
            get {
                return ResourceManager.GetString("ProjectsSharedMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small open-source or commercial projects with &lt;=2,000 lines of code that are used by others.
        /// </summary>
        internal static string ProjectsSharedSmall {
            get {
                return ResourceManager.GetString("ProjectsSharedSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In which kind of teams did you regularly work on a project in the last year:.
        /// </summary>
        internal static string Teams_Question {
            get {
                return ResourceManager.GetString("Teams_Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Large teams (&gt;=10 regular committers in the last year).
        /// </summary>
        internal static string TeamsLarge {
            get {
                return ResourceManager.GetString("TeamsLarge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium teams (&gt;3 and &lt;10 regular committers in the last year).
        /// </summary>
        internal static string TeamsMedium {
            get {
                return ResourceManager.GetString("TeamsMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Small teams (&lt;=3 regular committers in the last year).
        /// </summary>
        internal static string TeamsSmall {
            get {
                return ResourceManager.GetString("TeamsSmall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Projects with me as the only regular committer.
        /// </summary>
        internal static string TeamsSolo {
            get {
                return ResourceManager.GetString("TeamsSolo", resourceCulture);
            }
        }
    }
}
